# Generated by Django 3.2.6 on 2021-08-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0002_auto_20210803_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='productInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nameL', models.CharField(max_length=50)),
                ('nameE', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nameL', models.CharField(max_length=2500)),
                ('nameE', models.CharField(blank=True, max_length=2500, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('cusType', models.CharField(blank=True, choices=[('IND', 'Individual'), ('COM', 'Company'), ('UTI', 'Utility')], max_length=5, null=True)),
                ('enterpricecode', models.CharField(blank=True, max_length=25, null=True)),
                ('companyNameL', models.CharField(blank=True, max_length=550, null=True)),
                ('companyNameE', models.CharField(blank=True, max_length=550, null=True)),
                ('nationalId', models.CharField(max_length=20)),
                ('familyId', models.CharField(max_length=20)),
                ('passportId', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('productInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicNews.productinfo')),
            ],
        ),
    ]
