# Generated by Django 3.2.6 on 2021-08-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0004_newscommand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'ordering': ['-id'], 'verbose_name_plural': 'CustomerInfo'},
        ),
        migrations.AlterModelOptions(
            name='newscommand',
            options={'ordering': ['-id'], 'verbose_name_plural': 'news'},
        ),
    ]
