# Generated by Django 3.2.6 on 2021-08-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0005_auto_20210803_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='proType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.CharField(max_length=100)),
                ('nameE', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'proType',
            },
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ['-id'], 'verbose_name_plural': 'ProductInfo'},
        ),
        migrations.AddField(
            model_name='productinfo',
            name='descE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='descL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='insertDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pFiles',
            field=models.FileField(blank=True, null=True, upload_to='uploadProducts'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pimage',
            field=models.FileField(blank=True, null=True, upload_to='uploadProducts'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='nameL',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='proType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicNews.protype'),
        ),
    ]
