# Generated by Django 4.2 on 2025-02-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseInfo2',
            fields=[
                ('EnterpriseID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('LCICID', models.CharField(max_length=255)),
                ('enterpriseNameLao', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'EnterpriseInfo2',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soneserver1',
            fields=[
                ('EnterpriseID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('LCICID', models.CharField(max_length=255)),
                ('enterpriseNameLao', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Soneserver1',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soneserver2',
            fields=[
                ('EnterpriseID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('LCICID', models.CharField(max_length=255)),
                ('enterpriseNameLao', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Soneserver2',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
