# Generated by Django 4.2 on 2025-02-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEDCompanyInfo',
            fields=[
                ('CompanyID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CompanyInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NEDEnterpriseInfo',
            fields=[
                ('EnterpriseID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('LCICID', models.CharField(max_length=255)),
                ('enterpriseNameLao', models.CharField(max_length=255, null=True)),
                ('enterpriseNameEnglish', models.CharField(max_length=255, null=True)),
                ('regisCertificateNumber', models.CharField(max_length=255, null=True)),
                ('regisDate', models.DateTimeField(null=True)),
                ('enLocation', models.CharField(max_length=255, null=True)),
                ('regisStrationOfficeType', models.CharField(max_length=255, null=True)),
                ('regisStationOfficeCode', models.CharField(max_length=255, null=True)),
                ('enLegalStrature', models.CharField(max_length=255, null=True)),
                ('foreigninvestorFlag', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'EnterpriseInfo',
                'managed': False,
            },
        ),
    ]
