# Generated by Django 4.2 on 2025-02-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_batfile',
            name='fileName',
            field=models.CharField(max_length=500),
        ),
    ]
