# Generated by Django 3.2.6 on 2021-08-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_imagebar',
            name='imageS',
            field=models.FileField(blank=True, null=True, upload_to='UploadHome'),
        ),
    ]
