# Generated by Django 3.2.6 on 2021-08-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0002_h_imagebar_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='h_imagebar',
            options={'ordering': ['-id'], 'verbose_name_plural': 'ImageSlidBar'},
        ),
    ]
