# Generated by Django 4.2 on 2025-02-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0002_alter_search_batfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_batfile',
            name='duplicates_false',
            field=models.CharField(max_length=500),
        ),
    ]
