# Generated by Django 3.2.6 on 2021-08-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0003_alter_h_imagebar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='H_newsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.CharField(max_length=100)),
                ('nameE', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'newsType',
            },
        ),
        migrations.CreateModel(
            name='H_proType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.CharField(max_length=100)),
                ('nameE', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'proType',
            },
        ),
        migrations.CreateModel(
            name='H_userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('nameL', models.CharField(max_length=100)),
                ('nameE', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'userInfo',
            },
        ),
        migrations.CreateModel(
            name='H_productInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('nameL', models.CharField(max_length=250)),
                ('nameE', models.CharField(max_length=250)),
                ('descE', models.TextField(blank=True, null=True)),
                ('descL', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('pimage', models.FileField(blank=True, null=True, upload_to='uploadProducts')),
                ('pFiles', models.FileField(blank=True, null=True, upload_to='uploadProducts')),
                ('published', models.BooleanField(default=False)),
                ('insertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateDate', models.DateTimeField(auto_now=True, null=True)),
                ('proType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.h_protype')),
            ],
            options={
                'verbose_name_plural': 'ProductInfo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='H_newsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nameE', models.CharField(blank=True, max_length=100, null=True)),
                ('nameL', models.CharField(blank=True, max_length=100, null=True)),
                ('descE', models.TextField(blank=True, null=True)),
                ('descL', models.TextField(blank=True, null=True)),
                ('nimage', models.FileField(blank=True, null=True, upload_to='upload')),
                ('published', models.BooleanField(default=False)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('newsType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.h_newstype')),
                ('userInfo', models.ManyToManyField(blank=True, to='lcicHome.H_userInfo')),
            ],
        ),
        migrations.CreateModel(
            name='H_newsCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commandL', models.CharField(max_length=50)),
                ('commandE', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcicHome.h_newsinfo')),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-id'],
            },
        ),
    ]
