# Generated by Django 4.2 on 2025-02-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0003_alter_search_batfile_duplicates_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_batfile',
            name='path',
            field=models.CharField(max_length=500),
        ),
    ]
