# Generated by Django 4.2 on 2025-02-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0005_alter_search_batfile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_batfile',
            name='duplicates_false',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='search_batfile',
            name='fileName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='search_batfile',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
