# Generated by Django 4.2 on 2025-03-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0006_alter_search_batfile_duplicates_false_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseinfo',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
