# Generated by Django 4.2 on 2025-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0007_enterpriseinfo_lcic_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='b1',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b1_daily',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b1_monthly',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b1_yearly',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b_data_is_damaged',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data_edit',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disputes',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
