# Generated by Django 4.2 on 2025-04-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0008_b1_lcic_code_b1_daily_lcic_code_b1_monthly_lcic_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
