# Generated by Django 4.0.5 on 2022-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0008_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
