# Generated by Django 4.2 on 2025-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0008_systemuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='UID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
