# Generated by Django 4.2 on 2025-04-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0009_searchlog_lcic_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_charge',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
