# Generated by Django 4.2 on 2025-04-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0010_request_charge_lcic_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='LCIC_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
