# Generated by Django 4.2 on 2025-04-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0009_alter_login_uid'),
        ('lcicHome', '0011_searchresult_lcic_code'),
    ]

    operations = [
    ]
