# Generated by Django 4.2 on 2025-04-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0012_merge_20250410_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_bnk',
            name='bnk_images',
            field=models.ImageField(blank=True, null=True, upload_to='bank_images/'),
        ),
    ]
