# Generated by Django 4.2 on 2025-04-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0013_bank_bnk_bnk_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={},
        ),
    ]
