# Generated by Django 4.1 on 2023-01-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0014_billwater_customerwater_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='period',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
