# Generated by Django 4.2 on 2025-04-21 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0014_alter_systemuser_options_alter_systemuser_bnk_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCICSystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnk_code', models.CharField(max_length=10)),
                ('branch_code', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('roles', models.CharField(max_length=10)),
                ('nameL', models.CharField(max_length=100)),
                ('nameE', models.CharField(max_length=100)),
                ('surnameL', models.CharField(max_length=100)),
                ('surnameE', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('insertDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
