# Generated by Django 4.1 on 2023-01-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0015_upload_file_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwater',
            name='CompanyName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customerwater',
            name='NationalID',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customerwater',
            name='Passport',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
