# Generated by Django 4.2 on 2025-04-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0015_lcicsystemuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
