# Generated by Django 4.2 on 2025-04-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0016_delete_systemuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcicsystemuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
