# Generated by Django 4.1 on 2023-01-18 03:12

from django.db import migrations, models
import lcicHome.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0017_alter_upload_file_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='fileUpload',
            field=models.FileField(upload_to='media/fileUploads', validators=[lcicHome.validators.validate_file_extension]),
        ),
    ]
