# Generated by Django 4.2 on 2025-04-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0017_alter_lcicsystemuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='b1',
            name='status_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='b1_monthly',
            name='status_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
