# Generated by Django 4.2 on 2025-04-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0018_b1_status_data_b1_monthly_status_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='c1',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c1_disptes',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='c_error',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='col_goldsilver_gold',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='col_guarantor_com',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='col_guarantor_gua',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='col_money_mia',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='col_project_prj',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='col_real_estates',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='col_vechicle_veh',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
