# Generated by Django 4.2 on 2025-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0018_login_groups_login_user_permissions_alter_login_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name_lao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
