# Generated by Django 4.1 on 2023-01-31 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0019_alter_upload_file_fileupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerwater',
            options={'verbose_name_plural': 'CustomerWater'},
        ),
    ]
