# Generated by Django 4.2 on 2025-04-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0019_c1_lcic_code_c1_disptes_lcic_code_c_error_lcic_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c1',
            name='LCIC_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='col_real_estates',
            name='land_regis_date',
            field=models.CharField(null=True),
        ),
    ]
