# Generated by Django 4.2 on 2025-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0020_alter_c1_lcic_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c1_disptes',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='col_goldsilver_gold',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='col_guarantor_com',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='col_guarantor_gua',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='col_money_mia',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='col_project_prj',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='col_real_estates',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='col_vechicle_veh',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
