# Generated by Django 4.1 on 2023-02-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0020_alter_customerwater_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentType',
            fields=[
                ('SType', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='upload_file',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_file',
            name='updateDate',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_file',
            name='uploadType',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
