# Generated by Django 4.1 on 2023-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0021_segmenttype_upload_file_path_upload_file_updatedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenttype',
            name='SType',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
