# Generated by Django 4.2 on 2025-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0021_c1_disptes_data_status_col_equipment_eqi_data_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c1',
            name='data_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
