# Generated by Django 4.1 on 2023-02-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0022_alter_segmenttype_stype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SegmentType',
        ),
    ]
