# Generated by Django 4.2 on 2025-05-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0022_c1_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file_c',
            name='percentage',
            field=models.FloatField(default=0.0, max_length=255),
        ),
    ]
