# Generated by Django 4.2 on 2025-05-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0023_alter_upload_file_c_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_guarantor_gua',
            name='gua_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_guarantor_gua',
            name='user_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
