# Generated by Django 4.2 on 2025-05-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0024_col_guarantor_gua_gua_name_col_guarantor_gua_user_id'),
    ]

    operations = [
       migrations.AddField(
           model_name='col_guarantor_gua',
           name='insert_date',
           field=models.DateField(null=True, blank=True),  
       ),
       migrations.AddField(
           model_name='col_guarantor_gua',
           name='owner_gender',
           field=models.CharField(max_length=255, null=True, blank=True),  
       ),
       migrations.AddField(
           model_name='col_guarantor_gua',
           name='update_date',
           field=models.DateField(null=True, blank=True),  
       ),
   ]
