# Generated by Django 4.2 on 2025-05-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0025_col_guarantor_gua_insert_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_guarantor_gua',
            name='insert_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='col_guarantor_gua',
            name='update_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
