# Generated by Django 4.1 on 2023-02-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0025_upload_file_stype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_File',
        ),
    ]
