# Generated by Django 4.2 on 2025-05-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0026_alter_col_guarantor_gua_insert_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_real_estates',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='col_guarantor_gua',
            name='owner_gender',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
