# Generated by Django 4.1 on 2023-02-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0027_upload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
