# Generated by Django 4.2 on 2025-05-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0027_col_real_estates_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_real_estates',
            name='land_area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='col_real_estates',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
