# Generated by Django 4.1 on 2023-02-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0028_delete_uploads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_File',
        ),
    ]
