# Generated by Django 4.2 on 2025-09-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0019_role_name_lao'),
        ('lcicHome', '0028_alter_col_real_estates_land_area_and_more'),
    ]

    operations = [
    ]
