# Generated by Django 4.2 on 2025-09-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0029_merge_20250908_1137'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['Village_Name'], name='lcicHome_vi_Village_3a89c5_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['Prov_ID'], name='lcicHome_vi_Prov_ID_436cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['Dstr_ID'], name='lcicHome_vi_Dstr_ID_3e192a_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['Prov_ID', 'Dstr_ID'], name='lcicHome_vi_Prov_ID_925f5a_idx'),
        ),
    ]
