# Generated by Django 4.2 on 2025-09-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0030_village_lcichome_vi_village_3a89c5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_charge',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
