# Generated by Django 4.2 on 2025-09-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0031_alter_request_charge_lcic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_charge',
            name='LCIC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
