# Generated by Django 4.1 on 2023-02-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0031_rename_sname_segmenttype_namee_segmenttype_namel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='fileUpload',
            field=models.FileField(upload_to='uploadFiles/'),
        ),
    ]
