# Generated by Django 4.1 on 2023-03-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0032_alter_upload_file_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_IND_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_ind_sys_id', models.IntegerField(max_length=11)),
                ('bnk_code', models.CharField(max_length=10)),
                ('branchcode', models.CharField(max_length=30)),
                ('customerid', models.CharField(max_length=30)),
                ('ind_birth_date', models.DateField()),
                ('ind_name', models.CharField(max_length=100)),
                ('ind_second_name', models.CharField(max_length=30)),
                ('ind_surname', models.CharField(max_length=100)),
                ('ind_lao_name', models.TextField()),
                ('ind_lao_surname', models.TextField()),
                ('ind_old_surname', models.CharField(max_length=30)),
                ('ind_lao_old_surname', models.TextField()),
                ('ind_nationality', models.CharField(max_length=3)),
                ('ind_gender', models.CharField(max_length=1)),
                ('ind_civill_status', models.CharField(max_length=10)),
                ('ind_insert_date', models.DateTimeField(blank=True)),
                ('ind_update_date', models.DateTimeField(blank=True)),
                ('mm_action_date', models.DateTimeField(blank=True)),
                ('mm_log', models.CharField(max_length=10)),
                ('mm_comment', models.TextField()),
                ('mm_by', models.CharField(max_length=15)),
                ('blk_sys_id', models.IntegerField(max_length=11)),
                ('mm_status', models.CharField(max_length=1)),
                ('is_manual', models.CharField(max_length=1)),
                ('ind_lao_name_code', models.CharField(max_length=255)),
                ('ind_lao_surname_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_IND_Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_ind_sys_id', models.IntegerField(max_length=11)),
                ('bnk_code', models.CharField(max_length=10)),
                ('branchcode', models.CharField(max_length=30)),
                ('customerid', models.CharField(max_length=30)),
                ('ind_national_id', models.CharField(max_length=30)),
                ('ind_national_id_date', models.DateField()),
                ('ind_passport', models.CharField(max_length=30)),
                ('ind_passport_date', models.DateField()),
                ('ind_familybook', models.CharField(max_length=30)),
                ('ind_familybook_prov_code', models.CharField(max_length=20)),
                ('ind_familybook_date', models.DateField()),
            ],
        ),
    ]
