# Generated by Django 5.0.14 on 2025-09-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0032_alter_request_charge_lcic_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_batfile',
            name='not_report',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
