# Generated by Django 5.0.14 on 2025-09-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0033_search_batfile_not_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_batfile',
            name='not_report',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
