# Generated by Django 4.1 on 2023-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0033_customer_ind_info_customer_ind_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_ind_info',
            name='blk_sys_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer_ind_info',
            name='mm_ind_sys_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer_ind_keys',
            name='mm_ind_sys_id',
            field=models.IntegerField(default=0),
        ),
    ]
