# Generated by Django 4.2 on 2025-09-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0034_alter_search_batfile_not_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='b1',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
