# Generated by Django 4.1 on 2023-03-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0034_alter_customer_ind_info_blk_sys_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Info_IND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_ind_sys_id', models.IntegerField(default=0)),
                ('bnk_code', models.CharField(max_length=10)),
                ('branchcode', models.CharField(max_length=30)),
                ('customerid', models.CharField(max_length=30)),
                ('ind_birth_date', models.DateField()),
                ('ind_name', models.CharField(max_length=100)),
                ('ind_second_name', models.CharField(max_length=30)),
                ('ind_surname', models.CharField(max_length=100)),
                ('ind_lao_name', models.TextField()),
                ('ind_lao_surname', models.TextField()),
                ('ind_old_surname', models.CharField(max_length=30)),
                ('ind_lao_old_surname', models.TextField()),
                ('ind_nationality', models.CharField(max_length=3)),
                ('ind_gender', models.CharField(max_length=1)),
                ('ind_civill_status', models.CharField(max_length=10)),
                ('ind_insert_date', models.DateTimeField(blank=True)),
                ('ind_update_date', models.DateTimeField(blank=True)),
                ('mm_action_date', models.DateTimeField(blank=True)),
                ('blk_sys_id', models.IntegerField(default=0)),
                ('mm_status', models.CharField(max_length=1)),
            ],
        ),
    ]
