# Generated by Django 4.1 on 2023-03-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0035_customer_info_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Keys_IND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_ind_sys_id', models.IntegerField(default=0)),
                ('bnk_code', models.CharField(max_length=10)),
                ('branchcode', models.CharField(max_length=30)),
                ('customerid', models.CharField(max_length=30)),
                ('CKCode', models.CharField(max_length=30)),
                ('RegisDate', models.DateField()),
                ('VillCode', models.CharField(max_length=10)),
                ('KType', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=100)),
                ('insert_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
                ('userid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lcic_Info',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_ind_sys_id', models.IntegerField(default=0)),
                ('insert_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
                ('userid', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer_IND_Info',
        ),
    ]
