# Generated by Django 4.2 on 2025-09-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0035_b1_progress_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
