# Generated by Django 4.1 on 2023-03-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0036_customer_keys_ind_lcic_info_delete_customer_ind_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info_ind',
            old_name='ind_civill_status',
            new_name='ind_civil_status',
        ),
    ]
