# Generated by Django 5.0.14 on 2025-10-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0036_upload_file_progress_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_data_is_damaged',
            name='lcicID_get',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
