# Generated by Django 5.0.14 on 2025-10-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0037_alter_b_data_is_damaged_lcicid_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='LCIC_reques',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
