# Generated by Django 4.1 on 2023-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0038_alter_customer_info_ind_mm_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info_ind',
            name='mm_status',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
