# Generated by Django 5.0.14 on 2025-10-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0038_collateral_lcic_reques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='LCIC_reques',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='collateral',
            table='collateral',
        ),
    ]
