# Generated by Django 5.0.14 on 2025-10-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0039_alter_collateral_lcic_reques_alter_collateral_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='LCIC_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='enterpriseinfo',
            index=models.Index(fields=['LCIC_code'], name='enterprisei_LCIC_co_63d2ff_idx'),
        ),
        migrations.AlterModelTable(
            name='enterpriseinfo',
            table='enterpriseinfo',
        ),
    ]
