# Generated by Django 4.1 on 2023-03-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0039_alter_customer_info_ind_mm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info_ind',
            name='ind_old_surname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
