# Generated by Django 4.1 on 2023-03-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0040_alter_customer_info_ind_ind_old_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info_ind',
            name='ind_civil_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
