# Generated by Django 5.0.14 on 2025-10-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0040_alter_enterpriseinfo_lcic_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='updatedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
