# Generated by Django 4.1 on 2023-03-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0041_alter_customer_info_ind_ind_civil_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info_ind',
            name='mm_ind_sys_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
