# Generated by Django 5.0.14 on 2025-10-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0041_collateral_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
