# Generated by Django 4.1 on 2023-06-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0042_alter_customer_info_ind_mm_ind_sys_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='B1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprisecode', models.CharField(max_length=25)),
                ('lcicid', models.CharField(max_length=25)),
                ('segment', models.CharField(max_length=5)),
                ('bankcustomerid', models.CharField(max_length=30)),
                ('branchid', models.CharField(max_length=30)),
                ('loanid', models.CharField(max_length=30)),
                ('opendate', models.DateTimeField(blank=True)),
                ('expirydate', models.DateTimeField(blank=True)),
                ('extensiondate', models.DateTimeField(blank=True)),
                ('interestrate', models.FloatField(default=0, null=True)),
                ('purposecode', models.CharField(max_length=30)),
                ('creditline', models.IntegerField(default=0, null=True)),
                ('currencycode', models.CharField(max_length=10)),
                ('outstanding_balance', models.IntegerField(default=0, null=True)),
                ('loan_account_number', models.CharField(max_length=30)),
                ('number_of_days_slow', models.CharField(max_length=30)),
                ('loan_class', models.CharField(max_length=5)),
                ('loan_type', models.CharField(max_length=5)),
                ('loan_term', models.CharField(max_length=25)),
                ('loan_status', models.CharField(max_length=5)),
                ('date_time_update', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Info_IND_ERRORS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_ind_sys_id', models.IntegerField(default=0, null=True)),
                ('bnk_code', models.CharField(max_length=10)),
                ('branchcode', models.CharField(max_length=30)),
                ('customerid', models.CharField(max_length=30)),
                ('ind_birth_date', models.DateField()),
                ('ind_name', models.CharField(max_length=100)),
                ('ind_second_name', models.CharField(max_length=30)),
                ('ind_surname', models.CharField(max_length=100)),
                ('ind_lao_name', models.TextField()),
                ('ind_lao_surname', models.TextField()),
                ('ind_old_surname', models.CharField(max_length=30, null=True)),
                ('ind_lao_old_surname', models.TextField()),
                ('ind_nationality', models.CharField(max_length=3)),
                ('ind_gender', models.CharField(max_length=1)),
                ('ind_civil_status', models.CharField(max_length=10, null=True)),
                ('ind_insert_date', models.DateTimeField(blank=True)),
                ('ind_update_date', models.DateTimeField(blank=True)),
                ('mm_action_date', models.DateTimeField(blank=True, null=True)),
                ('blk_sys_id', models.IntegerField(default=0)),
                ('mm_status', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
