# Generated by Django 4.2 on 2025-10-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0042_alter_collateral_updatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name_la',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
