# Generated by Django 5.0.14 on 2025-10-15 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0043_role_name_la'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmDispustLoan',
            fields=[
                ('id_disput_loan', models.AutoField(primary_key=True, serialize=False)),
                ('bnk_code', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='disput_loan_images/')),
                ('user_insert', models.CharField(max_length=100)),
                ('user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('insertdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'confirm_dispust_loan',
            },
        ),
        migrations.CreateModel(
            name='disputes_noti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_file', models.CharField(max_length=100)),
                ('lcicID', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('com_enterprise_code', models.CharField(max_length=100)),
                ('segmentType', models.CharField(max_length=100)),
                ('bnk_code', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('branch_id', models.CharField(max_length=100)),
                ('lon_sys_id', models.CharField(max_length=100)),
                ('loan_id', models.CharField(max_length=100)),
                ('lon_open_date', models.DateField(null=True)),
                ('lon_exp_date', models.DateField(null=True)),
                ('lon_ext_date', models.DateField(null=True)),
                ('lon_int_rate', models.FloatField(default=0)),
                ('lon_purpose_code', models.CharField(max_length=100)),
                ('lon_credit_line', models.FloatField(default=0)),
                ('lon_currency_code', models.CharField(max_length=100)),
                ('lon_outstanding_balance', models.FloatField(default=0)),
                ('lon_account_no', models.CharField(max_length=100)),
                ('lon_no_days_slow', models.IntegerField(default=0)),
                ('lon_class', models.CharField(max_length=100)),
                ('lon_type', models.CharField(max_length=100)),
                ('lon_term', models.CharField(max_length=100)),
                ('lon_status', models.CharField(max_length=100)),
                ('lon_insert_date', models.DateTimeField(null=True)),
                ('lon_update_date', models.DateTimeField(null=True)),
                ('lon_applied_date', models.DateTimeField(null=True)),
                ('user_id', models.CharField(max_length=100)),
                ('is_disputed', models.BigIntegerField(default=0, null=True)),
                ('LCIC_code', models.CharField(blank=True, max_length=255, null=True)),
                ('confirm_dispust_id', models.ForeignKey(blank=True, db_column='confirm_dispust_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='lcicHome.confirmdispustloan')),
            ],
            options={
                'db_table': 'disputes_noti',
            },
        ),
    ]
