# Generated by Django 5.0.14 on 2025-10-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0044_confirmdispustloan_disputes_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='dispuste',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
