# Generated by Django 4.1 on 2023-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0045_delete_stype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SType', models.CharField(max_length=150)),
                ('nameL', models.CharField(blank=True, max_length=150)),
                ('nameE', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
