# Generated by Django 5.0.14 on 2025-10-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0045_upload_file_dispuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputes_noti',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
