# Generated by Django 5.0.14 on 2025-10-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0046_disputes_noti_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputes_noti',
            name='deception',
            field=models.TextField(blank=True, null=True),
        ),
    ]
