# Generated by Django 4.1 on 2023-06-19 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0046_stype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='SType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.stype'),
        ),
    ]
