# Generated by Django 4.1 on 2023-06-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0047_alter_upload_file_stype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='B1',
        ),
    ]
