# Generated by Django 5.0.14 on 2025-10-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0047_disputes_noti_deception'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='b1',
            index=models.Index(fields=['bnk_code', 'period'], name='lcicHome_b1_bnk_cod_3b5f02_idx'),
        ),
        migrations.AddIndex(
            model_name='b1',
            index=models.Index(fields=['period'], name='lcicHome_b1_period_9ae62f_idx'),
        ),
        migrations.AddIndex(
            model_name='b1',
            index=models.Index(fields=['id_file'], name='lcicHome_b1_id_file_bba711_idx'),
        ),
        migrations.AddIndex(
            model_name='b1',
            index=models.Index(fields=['com_enterprise_code'], name='lcicHome_b1_com_ent_f67fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='b1',
            index=models.Index(fields=['LCIC_code'], name='lcicHome_b1_LCIC_co_9cb764_idx'),
        ),
        migrations.AddIndex(
            model_name='b1',
            index=models.Index(fields=['status_data'], name='lcicHome_b1_status__155cff_idx'),
        ),
    ]
