# Generated by Django 4.2 on 2025-10-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0048_b1_lcichome_b1_bnk_cod_3b5f02_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputes',
            name='action_dispust',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
