# Generated by Django 5.0.14 on 2025-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0049_disputes_action_dispust'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputes',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disputes_noti',
            name='id_dispust',
            field=models.BigIntegerField(null=True),
        ),
    ]
