# Generated by Django 5.0.14 on 2025-10-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0050_disputes_status_disputes_noti_id_dispust'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputes_noti',
            name='action_dispust',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
