# Generated by Django 4.2 on 2025-10-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0051_disputes_noti_action_dispust'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmDispustCollateral',
            fields=[
                ('id_disput_loan', models.AutoField(primary_key=True, serialize=False)),
                ('bnk_code', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='disput_colateral_images/')),
                ('user_insert', models.CharField(max_length=100)),
                ('user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('insertdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='c1_disptes',
            name='action_dispust',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c1_disptes',
            name='is_disputed',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='c1_disptes',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_file_c',
            name='dispuste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='C1_disptes_noti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_file', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=150)),
                ('bnk_code', models.CharField(max_length=30)),
                ('segmentType', models.CharField(max_length=10)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('bank_customer_ID', models.CharField(max_length=50)),
                ('loan_id', models.CharField(max_length=50)),
                ('col_id', models.CharField(max_length=30)),
                ('col_type', models.CharField(max_length=30)),
                ('collateral_status', models.CharField(max_length=30)),
                ('insert_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
                ('lcicID', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=100)),
                ('com_enterprise_code', models.CharField(max_length=50)),
                ('data_status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_disputed', models.BigIntegerField(default=0, null=True)),
                ('LCIC_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=100)),
                ('action_dispust', models.CharField(max_length=100)),
                ('confirm_dispust_id', models.ForeignKey(blank=True, db_column='confirm_dispust_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='lcicHome.confirmdispustcollateral')),
            ],
        ),
    ]
