# Generated by Django 4.1 on 2023-06-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0051_a2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a2',
            old_name='loan_account_no',
            new_name='lon_account_no',
        ),
    ]
