# Generated by Django 4.1 on 2023-06-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0052_rename_loan_account_no_a2_lon_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a2',
            name='lon_ext_date',
            field=models.DateField(blank=True, default=0),
        ),
    ]
