# Generated by Django 4.2 on 2025-10-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0052_confirmdispustcollateral_c1_disptes_action_dispust_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebaritem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sidebarsubitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='sidebaritem',
            name='order',
            field=models.IntegerField(default=0, help_text='Sequence for layout (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='sidebarsubitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Sequence for layout under parent (lower numbers first)'),
        ),
    ]
