# Generated by Django 4.2 on 2025-10-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0052_confirmdispustcollateral_c1_disptes_action_dispust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c1_disptes',
            name='deception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c1_disptes_noti',
            name='deception',
            field=models.TextField(blank=True, null=True),
        ),
    ]
