# Generated by Django 5.0.14 on 2025-10-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0053_c1_disptes_deception_c1_disptes_noti_deception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdl',
            name='c1',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cdl',
            name='c3',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cdl',
            name='col_type',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cdl',
            name='id_file',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cdl',
            name='period',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='cdl',
            index=models.Index(fields=['id_file', 'col_type'], name='lcicHome_cd_id_file_7e883b_idx'),
        ),
        migrations.AddIndex(
            model_name='cdl',
            index=models.Index(fields=['c1', 'period', 'c3'], name='lcicHome_cd_c1_e1111c_idx'),
        ),
    ]
