# Generated by Django 4.2 on 2025-10-27 03:00

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0053_alter_sidebaritem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sidebaritem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sidebarsubitem',
            options={'ordering': ['parent__order', 'order', 'id']},
        ),
        migrations.RenameField(
            model_name='sidebaritem',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sidebarsubitem',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_access_all_paths',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name_la',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name_lao',
        ),
        migrations.RemoveField(
            model_name='sidebaritem',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sidebarsubitem',
            name='url',
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sidebaritem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebaritem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sidebaritem',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sidebaritem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sidebarsubitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebarsubitem',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sidebarsubitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sidebarsubitem',
            name='route',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebarsubitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sidebaritem',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sidebaritem',
            name='order',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sidebaritem',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='sidebar_items', to='lcicHome.role'),
        ),
        migrations.AlterField(
            model_name='sidebarsubitem',
            name='order',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sidebarsubitem',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='sidebar_sub_items', to='lcicHome.role'),
        ),
        migrations.AddIndex(
            model_name='sidebaritem',
            index=models.Index(fields=['order', 'id'], name='sidebar_ite_order_42958e_idx'),
        ),
        migrations.AddIndex(
            model_name='sidebarsubitem',
            index=models.Index(fields=['parent', 'order', 'id'], name='sidebar_sub_parent__dcd41d_idx'),
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='sidebaritem',
            table='sidebar_items',
        ),
        migrations.AlterModelTable(
            name='sidebarsubitem',
            table='sidebar_sub_items',
        ),
    ]
