# Generated by Django 4.2 on 2025-10-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0054_alter_role_options_alter_sidebaritem_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sidebaritem',
            new_name='lcicHome_si_order_32b154_idx',
            old_name='sidebar_ite_order_42958e_idx',
        ),
        migrations.RenameIndex(
            model_name='sidebarsubitem',
            new_name='lcicHome_si_parent__d8689a_idx',
            old_name='sidebar_sub_parent__dcd41d_idx',
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sidebaritem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sidebarsubitem',
            table=None,
        ),
    ]
