# Generated by Django 4.2 on 2025-10-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0054_alter_cdl_c1_alter_cdl_c3_alter_cdl_col_type_and_more'),
    ]

    operations = [
    ]
