# Generated by Django 4.1 on 2023-06-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0054_alter_a2_lcicid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A2',
        ),
    ]
