# Generated by Django 4.2.16 on 2025-10-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0055_auto_20251027_1110'),
        ('lcicHome', '0055_rename_sidebar_ite_order_42958e_idx_lcichome_si_order_32b154_idx_and_more'),
    ]

    operations = [
    ]
