# Generated by Django 4.2 on 2025-10-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0026_alter_memberinfo_code_alter_memberinfo_slug'),
        ('lcicHome', '0058_companyinfomapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File_Individual',
            fields=[
                ('FID', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=255)),
                ('fileName', models.CharField(max_length=255)),
                ('fileUpload', models.FileField(upload_to='uploadFilesIdividual/')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('fileSize', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('statussubmit', models.CharField(max_length=150)),
                ('status_upload', models.CharField(max_length=150)),
                ('FileType', models.CharField(max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
                ('dispuste', models.CharField(blank=True, max_length=255, null=True)),
                ('GID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.user_group')),
                ('MID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicNews.memberinfo')),
                ('SType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.stype')),
                ('UType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.upload_type')),
            ],
        ),
    ]
