# Generated by Django 4.1 on 2023-06-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0058_a2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A2',
        ),
    ]
