# Generated by Django 4.2 on 2025-11-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0056_merge_20251029_0950'),
        ('lcicHome', '0059_upload_file_individual'),
    ]

    operations = [
    ]
