# Generated by Django 4.2 on 2025-11-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0060_merge_20251102_1447'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='data_edit',
            index=models.Index(fields=['id_file'], name='idx_data_edit_file'),
        ),
        migrations.AddIndex(
            model_name='data_edit',
            index=models.Index(fields=['bnk_code', 'branch_id', 'customer_id', 'loan_id', 'period'], name='idx_data_edit_composite'),
        ),
    ]
