# Generated by Django 5.0.14 on 2025-11-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0062_upload_file_individual_collateral'),
        ('lcicHome', '0063_alter_useraccesslog_user'),
    ]

    operations = [
    ]
