# Generated by Django 4.2.16 on 2025-11-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0062_upload_file_individual_collateral'),
        ('lcicHome', '0063_alter_useraccesslog_user'),
    ]

    operations = [
    ]
