# Generated by Django 4.1 on 2023-06-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0063_b1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a2',
            name='lon_ext_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_ext_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
