# Generated by Django 4.2 on 2025-11-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0062_upload_file_individual_collateral'),
        ('lcicHome', '0063_alter_useraccesslog_user'),
    ]

    operations = [
    ]
