# Generated by Django 5.0.14 on 2025-11-11 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0064_merge_20251111_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCustomerWhitEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterpriseID', models.CharField(blank=True, max_length=50, null=True)),
                ('customerID', models.CharField(blank=True, max_length=50, null=True)),
                ('LCIC_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('user_insert', models.CharField(blank=True, max_length=100, null=True)),
                ('user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseMemberSubmit',
            fields=[
                ('LCICID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterpriseID', models.CharField(blank=True, max_length=50, null=True)),
                ('enterpriseNameLao', models.CharField(blank=True, max_length=255, null=True)),
                ('eneterpriseNameEnglish', models.CharField(blank=True, max_length=255, null=True)),
                ('regisCertificateNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('regisDate', models.DateTimeField(blank=True, null=True)),
                ('enLocation', models.CharField(blank=True, max_length=50, null=True)),
                ('regisStrationOfficeType', models.CharField(blank=True, max_length=50, null=True)),
                ('regisStationOfficeCode', models.CharField(blank=True, max_length=50, null=True)),
                ('enLegalStrature', models.CharField(blank=True, max_length=500, null=True)),
                ('foreigninvestorFlag', models.CharField(blank=True, max_length=500, null=True)),
                ('investmentAmount', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('investmentCurrency', models.CharField(blank=True, max_length=50, null=True)),
                ('representativeNationality', models.CharField(blank=True, max_length=50, null=True)),
                ('LastUpdate', models.DateTimeField(blank=True, null=True)),
                ('user_insert', models.CharField(blank=True, max_length=100, null=True)),
                ('user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('CancellationDate', models.DateTimeField(blank=True, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
                ('LCIC_code', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('id_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.uploadfile_enterpriseinfo')),
            ],
            options={
                'db_table': 'enterprisemember_submit',
                'indexes': [models.Index(fields=['LCIC_code'], name='enterprisem_LCIC_co_9abcb2_idx')],
            },
        ),
    ]
