# Generated by Django 4.1 on 2023-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0064_alter_a2_lon_ext_date_alter_b1_lon_ext_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a2',
            name='bnk_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='a2',
            name='lon_class',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='a2',
            name='lon_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='a2',
            name='lon_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='a2',
            name='segmentType',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_class',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='b1',
            name='segmentType',
            field=models.CharField(max_length=10),
        ),
    ]
