# Generated by Django 4.2.16 on 2025-11-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0064_merge_20251110_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='scr_atttype_desc',
            fields=[
                ('id_desc', models.AutoField(primary_key=True, serialize=False)),
                ('att_type', models.CharField(max_length=50)),
                ('att_type_desc', models.CharField(max_length=100)),
                ('att_type_lao_desc', models.CharField(max_length=100)),
                ('att_weight', models.IntegerField()),
            ],
        ),
    ]
