# Generated by Django 4.2 on 2025-11-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0064_merge_20251110_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualBankIbk_MapLog',
            fields=[
                ('ind_sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('lcic_id', models.CharField(blank=True, max_length=150, null=True)),
                ('segment', models.CharField(blank=True, max_length=150, null=True)),
                ('mm_ind_sys_id', models.CharField(blank=True, max_length=150, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=150, null=True)),
                ('branchcode', models.CharField(blank=True, max_length=150, null=True)),
                ('customerid', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_national_id', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_national_id_date', models.DateField(blank=True, null=True)),
                ('ind_passport', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_passport_date', models.DateField(blank=True, null=True)),
                ('ind_familybook', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_familybook_prov_code', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_familybook_date', models.DateField(blank=True, null=True)),
                ('ind_birth_date', models.DateField(blank=True, null=True)),
                ('ind_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_second_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_lao_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_lao_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_old_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_lao_old_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_nationality', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('ind_civil_status', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_insert_date', models.DateTimeField(blank=True, null=True)),
                ('ind_update_date', models.DateTimeField(blank=True, null=True)),
                ('mm_action_date', models.DateTimeField(blank=True, null=True)),
                ('mm_log', models.TextField(blank=True, null=True)),
                ('mm_comment', models.TextField(blank=True, null=True)),
                ('mm_by', models.CharField(blank=True, max_length=150, null=True)),
                ('blk_sys_id', models.CharField(blank=True, max_length=150, null=True)),
                ('mm_status', models.CharField(blank=True, max_length=150, null=True)),
                ('is_manual', models.BooleanField(blank=True, null=True)),
                ('ind_lao_name_code', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_lao_surname_code', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualBankIbkInfo_CreateLog',
            fields=[
                ('ind_sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('mm_ind_sys_id', models.CharField(blank=True, max_length=150, null=True)),
                ('lcic_id', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_national_id', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_national_id_date', models.DateField(blank=True, null=True)),
                ('ind_passport', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_passport_date', models.DateField(blank=True, null=True)),
                ('ind_familybook', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_familybook_prov_code', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_familybook_date', models.DateField(blank=True, null=True)),
                ('ind_birth_date', models.DateField(blank=True, null=True)),
                ('ind_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_lao_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_lao_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('insert_by', models.CharField(blank=True, max_length=150, null=True)),
                ('update_by', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='individual_documents/')),
            ],
        ),
    ]
