# Generated by Django 5.0.14 on 2025-11-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0064_merge_20251111_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_catalog_cat',
            fields=[
                ('sub_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('main_id', models.IntegerField()),
                ('ct_type', models.CharField(max_length=30)),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_lao_name', models.CharField(max_length=100)),
                ('cat_value', models.CharField(max_length=100)),
                ('cat_is_default', models.IntegerField()),
                ('cat_sort_order', models.IntegerField()),
                ('cat_group', models.IntegerField(blank=True, null=True)),
                ('cat_status', models.IntegerField()),
            ],
        ),
    ]
