# Generated by Django 5.0.14 on 2025-11-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0065_registercustomerwhitenterprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LCIC_code', models.CharField(blank=True, max_length=100, null=True)),
                ('SegmentType', models.CharField(blank=True, max_length=50, null=True)),
                ('Customer_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('user_insert', models.CharField(blank=True, max_length=100, null=True)),
                ('user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
                ('DeleteDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LCIC_code', models.CharField(blank=True, max_length=100, null=True)),
                ('SegmentType', models.CharField(blank=True, max_length=50, null=True)),
                ('Customer_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('user_insert', models.CharField(blank=True, max_length=100, null=True)),
                ('user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
                ('DeleteDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LCIC_code', models.CharField(blank=True, max_length=100, null=True)),
                ('SegmentType', models.CharField(blank=True, max_length=50, null=True)),
                ('Customer_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('user_insert', models.CharField(blank=True, max_length=100, null=True)),
                ('user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
                ('DeleteDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_File_Borrower',
            fields=[
                ('FID', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=255)),
                ('fileName', models.CharField(max_length=255)),
                ('fileUpload', models.FileField(upload_to='borrower/')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('fileSize', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('statussubmit', models.CharField(max_length=150)),
                ('status_upload', models.CharField(max_length=150)),
                ('FileType', models.CharField(max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
                ('dispuste', models.CharField(blank=True, max_length=255, null=True)),
                ('SType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.stype')),
                ('UType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.upload_type')),
            ],
        ),
    ]
