# Generated by Django 5.0.14 on 2025-11-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0065_sub_catalog_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_type_cat',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_type', models.CharField(max_length=30)),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_lao_name', models.CharField(max_length=100)),
                ('cat_status', models.IntegerField()),
                ('cat_detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='sub_catalog_cat',
        ),
    ]
