# Generated by Django 4.1 on 2023-06-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0065_alter_a2_bnk_code_alter_a2_lon_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a2',
            name='is_disputed',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='a2',
            name='lon_credit_line',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='a2',
            name='lon_outstanding_balance',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_credit_line',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_outstanding_balance',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
