# Generated by Django 4.2 on 2025-11-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0065_individualbankibk_maplog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lcic_id', models.CharField(db_index=True, max_length=150)),
                ('identifier_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('FAMILY_BOOK', 'Family Book')], max_length=20)),
                ('identifier_value', models.CharField(max_length=150)),
                ('identifier_date', models.DateField(blank=True, null=True)),
                ('province_code', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingCandidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_ind_sys_id', models.IntegerField()),
                ('target_ind_sys_id', models.IntegerField()),
                ('source_lcic_id', models.CharField(blank=True, max_length=150, null=True)),
                ('target_lcic_id', models.CharField(blank=True, max_length=150, null=True)),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match_details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved/Merged'), ('REJECTED', 'Rejected'), ('AUTO_MATCHED', 'Auto Matched')], default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MergeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('MERGE', 'Merge'), ('UNMERGE', 'Unmerge')], max_length=10)),
                ('master_lcic_id', models.CharField(max_length=150)),
                ('merged_ind_sys_ids', models.JSONField()),
                ('merged_data', models.JSONField()),
                ('performed_by', models.CharField(max_length=150)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='mergehistory',
            index=models.Index(fields=['master_lcic_id'], name='lcicHome_me_master__f9c69a_idx'),
        ),
        migrations.AddIndex(
            model_name='mergehistory',
            index=models.Index(fields=['performed_at'], name='lcicHome_me_perform_05cafa_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingcandidate',
            index=models.Index(fields=['status', 'similarity_score'], name='lcicHome_ma_status_f6abdb_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingcandidate',
            index=models.Index(fields=['source_lcic_id'], name='lcicHome_ma_source__178d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingcandidate',
            index=models.Index(fields=['target_lcic_id'], name='lcicHome_ma_target__0f0f53_idx'),
        ),
        migrations.AddIndex(
            model_name='individualidentifier',
            index=models.Index(fields=['lcic_id', 'is_active'], name='lcicHome_in_lcic_id_611724_idx'),
        ),
        migrations.AddIndex(
            model_name='individualidentifier',
            index=models.Index(fields=['identifier_type', 'identifier_value'], name='lcicHome_in_identif_f4b645_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='individualidentifier',
            unique_together={('identifier_type', 'identifier_value', 'is_active')},
        ),
    ]
