# Generated by Django 4.2.16 on 2025-11-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0065_scr_atttype_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='scr_attribute_table',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('att_type', models.CharField(max_length=50)),
                ('att_name', models.CharField(max_length=50)),
                ('att_code', models.CharField(max_length=50)),
                ('att_value', models.IntegerField()),
            ],
        ),
    ]
