# Generated by Django 5.0.14 on 2025-11-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0066_borrower_borrowererror_borrowergood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerMonhtly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LCIC_code', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('SegmentType', models.CharField(blank=True, max_length=50, null=True)),
                ('Customer_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('user_insert', models.CharField(blank=True, max_length=100, null=True)),
                ('user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
                ('DeleteDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowererror',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowergood',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
