# Generated by Django 5.0.14 on 2025-11-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0066_catalog_type_cat_delete_sub_catalog_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_type_cat',
            name='cat_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
