# Generated by Django 5.0.14 on 2025-11-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0067_alter_catalog_type_cat_cat_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_type_cat',
            name='cat_type',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
