# Generated by Django 4.1 on 2023-08-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0067_delete_b1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A2',
            new_name='B1',
        ),
    ]
