# Generated by Django 5.0.14 on 2025-11-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0067_borrowermonhtly_borrower_period_borrowererror_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_file_borrower',
            old_name='FID',
            new_name='BID',
        ),
    ]
