# Generated by Django 5.0.14 on 2025-11-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0068_alter_catalog_type_cat_cat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_catalog_cat',
            name='cat_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
