# Generated by Django 5.0.14 on 2025-11-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0068_rename_fid_upload_file_borrower_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='EenterpriseID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='id_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.upload_file_borrower'),
        ),
        migrations.AddField(
            model_name='borrowererror',
            name='CodeError',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='borrowererror',
            name='EenterpriseID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowererror',
            name='id_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.upload_file_borrower'),
        ),
        migrations.AddField(
            model_name='borrowergood',
            name='EenterpriseID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowergood',
            name='id_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.upload_file_borrower'),
        ),
        migrations.AddField(
            model_name='borrowermonhtly',
            name='EenterpriseID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowermonhtly',
            name='id_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.upload_file_borrower'),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['bnk_code', 'SegmentType'], name='lcicHome_bo_bnk_cod_baf6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['period'], name='lcicHome_bo_period_4f2bf9_idx'),
        ),
    ]
