# Generated by Django 5.0.14 on 2025-11-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0069_alter_main_catalog_cat_cat_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_catalog_cat',
            name='cat_lao_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_catalog_cat',
            name='cat_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
