# Generated by Django 5.0.14 on 2025-11-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0069_borrower_eenterpriseid_borrower_id_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='segmentTypeBorrower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowererror',
            name='segmentTypeBorrower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowergood',
            name='segmentTypeBorrower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowermonhtly',
            name='segmentTypeBorrower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
