# Generated by Django 5.0.14 on 2025-11-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0070_borrower_segmenttypeborrower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='loan_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowererror',
            name='loan_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowergood',
            name='loan_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowermonhtly',
            name='loan_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
