# Generated by Django 5.0.14 on 2025-11-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0066_individualidentifier_matchingcandidate_mergehistory_and_more'),
        ('lcicHome', '0066_scr_attribute_table'),
        ('lcicHome', '0071_borrower_loan_id_borrowererror_loan_id_and_more'),
    ]

    operations = [
    ]
