# Generated by Django 5.0.14 on 2025-11-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0072_merge_20251113_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='LCIC_code_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='branch_id_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='customer_id_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowererror',
            name='LCIC_code_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowererror',
            name='branch_id_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowererror',
            name='customer_id_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowergood',
            name='LCIC_code_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowergood',
            name='branch_id_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowergood',
            name='customer_id_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowermonhtly',
            name='LCIC_code_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowermonhtly',
            name='branch_id_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowermonhtly',
            name='customer_id_brw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
