# Generated by Django 4.1 on 2023-08-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0072_rename_uploadtype_upload_file_filetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UType', models.CharField(max_length=3)),
                ('nameL', models.CharField(max_length=50)),
                ('nameE', models.CharField(max_length=50)),
            ],
        ),
    ]
