# Generated by Django 4.2 on 2025-11-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0072_merge_20251114_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergehistory',
            name='action',
            field=models.CharField(choices=[('MERGE', 'Merge'), ('UNMERGE', 'Unmerge')], max_length=100),
        ),
    ]
