# Generated by Django 4.2 on 2025-11-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0073_alter_mergehistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualbankibkinfo_createlog',
            name='bnk_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
