# Generated by Django 5.0.14 on 2025-11-13 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0073_borrower_lcic_code_brw_borrower_branch_id_brw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='collateral_images/')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('insertdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('pathfile', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=100)),
                ('LCIC_reques', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'collateral_new',
            },
        ),
        migrations.AlterField(
            model_name='enterprisemembersubmit',
            name='id_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.collateralnew'),
        ),
    ]
