# Generated by Django 4.2 on 2025-11-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0074_individualbankibkinfo_createlog_bnk_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualbankibkinfo_createlog',
            name='mm_ind_sys_id',
        ),
    ]
