# Generated by Django 5.0.14 on 2025-11-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0074_collateralnew_alter_enterprisemembersubmit_id_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralnew',
            name='decaption',
            field=models.TextField(null=True),
        ),
    ]
