# Generated by Django 4.1 on 2023-08-22 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0074_upload_file_utype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_File',
        ),
    ]
