# Generated by Django 4.2.16 on 2025-11-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0064_merge_20251110_1707'),
        ('lcicHome', '0075_collateralnew_decaption'),
    ]

    operations = [
    ]
