# Generated by Django 5.0.14 on 2025-11-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0064_merge_20251110_1707'),
        ('lcicHome', '0070_alter_main_catalog_cat_cat_lao_name_and_more'),
        ('lcicHome', '0075_collateralnew_decaption'),
    ]

    operations = [
    ]
