# Generated by Django 4.1 on 2023-08-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0015_h_lang'),
        ('lcicHome', '0075_delete_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('FID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('fileUpload', models.FileField(upload_to='uploadFiles/')),
                ('fileSize', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('status_upload', models.CharField(max_length=150)),
                ('FileType', models.CharField(max_length=10)),
                ('GID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.user_group')),
                ('MID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicNews.memberinfo')),
                ('SType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.stype')),
                ('UType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.upload_type')),
            ],
        ),
    ]
