# Generated by Django 4.2 on 2025-11-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0075_remove_individualbankibkinfo_createlog_mm_ind_sys_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualbankibkinfo_createlog',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='individualbankibkinfo_createlog',
            name='customer_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
