# Generated by Django 4.1 on 2023-08-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0076_upload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_File',
        ),
    ]
