# Generated by Django 4.2 on 2025-11-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0076_individualbankibkinfo_createlog_bank_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualBankIbkInfo_Register',
            fields=[
                ('ind_sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('lcic_id', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_national_id', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_national_id_date', models.DateField(blank=True, null=True)),
                ('ind_passport', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_passport_date', models.DateField(blank=True, null=True)),
                ('ind_familybook', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_familybook_prov_code', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_familybook_date', models.DateField(blank=True, null=True)),
                ('ind_birth_date', models.DateField(blank=True, null=True)),
                ('ind_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_lao_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ind_lao_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('insert_by', models.CharField(blank=True, max_length=150, null=True)),
                ('update_by', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lcic_registerd_date', models.DateField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='individual_documents/')),
            ],
        ),
        migrations.AddField(
            model_name='individualbankibkinfo_createlog',
            name='lcic_registerd_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
