# Generated by Django 4.2 on 2025-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0077_individualbankibkinfo_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbankibkinfo_createlog',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='individual_documents/log/'),
        ),
    ]
