# Generated by Django 4.2.16 on 2025-11-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0078_alter_individualbankibkinfo_createlog_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualbankibkinfo_register',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualbankibkinfo_register',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='individualbankibkinfo_register',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='individualbankibkinfo_register',
            index=models.Index(fields=['is_confirmed'], name='lcicHome_in_is_conf_27bf6a_idx'),
        ),
        migrations.AddIndex(
            model_name='individualbankibkinfo_register',
            index=models.Index(fields=['insert_by'], name='lcicHome_in_insert__fccd2c_idx'),
        ),
    ]
