# Generated by Django 4.1 on 2023-08-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0079_bank_bnk_bank_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank_branch',
        ),
    ]
