# Generated by Django 4.2.16 on 2025-11-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0075_collateralnew_decaption'),
        ('lcicHome', '0079_individualbankibkinfo_register_confirmed_at_and_more'),
    ]

    operations = [
    ]
