# Generated by Django 4.2.16 on 2025-11-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0080_merge_20251118_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualbankibkinfo_register',
            name='custype',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='individualbankibkinfo_register',
            name='segment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
