# Generated by Django 4.1 on 2023-08-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0080_delete_bank_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_branch',
            fields=[
                ('branch_sys_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=15)),
                ('branch_name', models.CharField(max_length=50)),
                ('Vill', models.CharField(max_length=50)),
                ('Dis', models.CharField(max_length=50)),
                ('Province', models.CharField(max_length=50)),
                ('bnk_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcicHome.bank_bnk')),
            ],
        ),
    ]
