# Generated by Django 4.2.16 on 2025-11-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0064_merge_20251110_1707'),
        ('lcicHome', '0070_alter_main_catalog_cat_cat_lao_name_and_more'),
        ('lcicHome', '0081_individualbankibkinfo_register_custype_and_more'),
    ]

    operations = [
    ]
