# Generated by Django 4.2.16 on 2025-11-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0082_merge_20251118_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='scr_attribute_table_new',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('att_type', models.CharField(max_length=50)),
                ('att_name', models.CharField(max_length=50)),
                ('att_code', models.CharField(max_length=50)),
                ('att_value', models.IntegerField()),
                ('att_group_id', models.CharField(max_length=5)),
                ('att_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='scr_atttype_desc_new',
            fields=[
                ('id_desc', models.AutoField(primary_key=True, serialize=False)),
                ('att_type', models.CharField(max_length=50)),
                ('att_type_desc', models.CharField(max_length=100)),
                ('att_type_lao_desc', models.CharField(max_length=100)),
                ('att_weight', models.IntegerField()),
            ],
        ),
    ]
