# Generated by Django 5.0.14 on 2025-11-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0082_merge_20251118_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfoMappingMemberSubmit',
            fields=[
                ('com_sys_id', models.IntegerField(primary_key=True, serialize=False)),
                ('segment', models.CharField(blank=True, max_length=5, null=True)),
                ('mm_com_sys_id', models.IntegerField(blank=True, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=10, null=True)),
                ('branchcode', models.CharField(blank=True, max_length=30, null=True)),
                ('customerid', models.CharField(blank=True, max_length=30, null=True)),
                ('com_enterprise_code', models.CharField(blank=True, max_length=30, null=True)),
                ('com_registration_date', models.CharField(blank=True, max_length=30, null=True)),
                ('com_registration_place_issue', models.TextField(blank=True, null=True)),
                ('com_name', models.CharField(blank=True, max_length=100, null=True)),
                ('com_lao_name', models.TextField(blank=True, null=True)),
                ('com_tax_no', models.CharField(blank=True, max_length=25, null=True)),
                ('com_category', models.CharField(blank=True, max_length=50, null=True)),
                ('com_regulatory_capital', models.CharField(blank=True, max_length=50, null=True)),
                ('com_regulatory_capital_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('com_insert_date', models.CharField(blank=True, max_length=30, null=True)),
                ('com_update_date', models.CharField(blank=True, max_length=30, null=True)),
                ('mm_action_date', models.CharField(blank=True, max_length=30, null=True)),
                ('mm_log', models.CharField(blank=True, max_length=50, null=True)),
                ('mm_comment', models.TextField(blank=True, null=True)),
                ('mm_by', models.CharField(blank=True, max_length=50, null=True)),
                ('blk_sys_id', models.IntegerField(blank=True, null=True)),
                ('mm_status', models.CharField(blank=True, max_length=1, null=True)),
                ('is_manual', models.CharField(blank=True, max_length=1, null=True)),
                ('com_lao_name_code', models.CharField(blank=True, max_length=255, null=True)),
                ('LCIC_code', models.CharField(blank=True, max_length=255, null=True)),
                ('enterprise_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MactCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=100)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('insertdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('pathfile', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=100)),
                ('LCIC_reques', models.CharField(blank=True, max_length=100, null=True)),
                ('decaption', models.TextField(null=True)),
            ],
            options={
                'db_table': 'mactcustomer',
            },
        ),
    ]
