# Generated by Django 5.0.14 on 2025-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0083_companyinfomappingmembersubmit_mactcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfomappingmembersubmit',
            name='id_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
