# Generated by Django 4.2.16 on 2025-11-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0083_scr_attribute_table_new_scr_atttype_desc_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scr_attribute_table_new',
            name='att_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scr_attribute_table_new',
            name='att_group_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='scr_atttype_desc_new',
            name='att_type_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scr_atttype_desc_new',
            name='att_type_lao_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
