# Generated by Django 5.0.14 on 2025-11-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0084_companyinfomappingmembersubmit_id_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfomappingmembersubmit',
            name='com_sys_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
