# Generated by Django 4.2.16 on 2025-11-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0076_merge_20251118_1553'),
        ('lcicHome', '0084_alter_scr_attribute_table_new_att_desc_and_more'),
    ]

    operations = [
    ]
