# Generated by Django 5.0.14 on 2025-11-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0076_merge_20251118_1553'),
        ('lcicHome', '0084_alter_scr_attribute_table_new_att_desc_and_more'),
        ('lcicHome', '0085_alter_companyinfomappingmembersubmit_com_sys_id'),
    ]

    operations = [
    ]
