# Generated by Django 5.0.14 on 2025-11-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0086_merge_20251119_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisemembersubmit',
            name='LCIC_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
