# Generated by Django 4.2.16 on 2025-11-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0086_merge_20251119_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='scr_atttype_desc_dy',
            fields=[
                ('id_desc', models.AutoField(primary_key=True, serialize=False)),
                ('att_type', models.CharField(max_length=50, unique=True)),
                ('att_type_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('att_type_lao_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('att_weight', models.IntegerField()),
                ('calculation_method', models.CharField(choices=[('simple', 'Simple Match - Direct code match'), ('range', 'Range Match - Value falls in range'), ('min_max', 'MIN/MAX - Get min or max from multiple loans'), ('custom', 'Custom Logic - Special calculation')], default='simple', help_text='How to calculate score for this parameter', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this parameter')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in report (1, 2, 3...)')),
                ('group_name', models.CharField(blank=True, choices=[('Personal Info', 'Personal Info'), ('Payment History', 'Payment History'), ('Amount Owned', 'Amount Owned'), ('Inquiries', 'Inquiries & Purpose'), ('Collateral', 'Collateral')], help_text='Group for dashboard display', max_length=100, null=True)),
                ('data_source', models.CharField(blank=True, choices=[('customer', 'Customer Info'), ('loan', 'Loan Summary'), ('collateral', 'Collateral Summary'), ('inquiry', 'Inquiry Data')], help_text='Where to get the input value from', max_length=50, null=True)),
                ('field_name', models.CharField(blank=True, help_text="Field name in data source (e.g., 'age', 'civil_status')", max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this parameter measures', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scoring Parameter',
                'verbose_name_plural': 'Scoring Parameters',
                'ordering': ['display_order'],
            },
        ),
    ]
