# Generated by Django 4.2.16 on 2025-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0087_scr_atttype_desc_dy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProductAccess',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('bnk_code', models.CharField(max_length=10)),
                ('chg_sys_id', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Member Product Accesses',
                'ordering': ['-created_at'],
                'unique_together': {('bnk_code', 'chg_sys_id')},
            },
        ),
    ]
