# Generated by Django 4.1 on 2023-08-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0088_bank_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank_branch',
        ),
    ]
