# Generated by Django 5.0.14 on 2025-11-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0085_merge_20251121_1546'),
        ('lcicHome', '0087_alter_enterprisemembersubmit_lcic_code'),
        ('lcicHome', '0088_memberproductaccess'),
    ]

    operations = [
    ]
