# Generated by Django 4.1 on 2023-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0089_delete_bank_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_branch',
            fields=[
                ('branch_sys_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnk_code', models.CharField(max_length=10)),
                ('branch_id', models.CharField(max_length=15)),
                ('branch_name', models.CharField(max_length=50)),
                ('Vill', models.CharField(max_length=50)),
                ('Dis', models.CharField(max_length=50)),
                ('Province', models.CharField(max_length=50)),
            ],
        ),
    ]
