# Generated by Django 4.1 on 2023-09-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0090_bank_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseInfo',
            fields=[
                ('LCICID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='LCICID')),
                ('EnterpriseID', models.CharField(max_length=50)),
                ('enterpriseNameLao', models.CharField(max_length=255)),
                ('eneterpriseNameEnglish', models.CharField(max_length=255)),
                ('regisCertificateNumber', models.CharField(max_length=50)),
                ('regisDate', models.DateTimeField(blank=True)),
                ('enLocation', models.CharField(max_length=50)),
                ('regisStrationOfficeType', models.CharField(max_length=50)),
                ('regisStationOfficeCode', models.CharField(max_length=50)),
                ('enLegalStrature', models.CharField(max_length=500)),
                ('foreigninvestorFlag', models.CharField(max_length=500)),
                ('investmentAmount', models.FloatField(blank=True, null=True)),
                ('investmentCurrency', models.CharField(max_length=50)),
                ('representativeNationality', models.CharField(max_length=50)),
                ('LastUpdate', models.DateTimeField(blank=True, null=True)),
                ('CancellationDate', models.DateTimeField(blank=True, null=True)),
                ('InsertDate', models.DateTimeField(blank=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
