# Generated by Django 5.0.14 on 2025-11-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0076_merge_20251121_1122'),
        ('lcicHome', '0091_lciccodemaping'),
    ]

    operations = [
    ]
