# Generated by Django 4.2.16 on 2025-11-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0076_merge_20251121_1122'),
        ('lcicHome', '0091_lciccodemaping'),
    ]

    operations = [
    ]
