# Generated by Django 4.2.16 on 2025-11-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0092_merge_0076_merge_20251121_1122_0091_lciccodemaping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='scr_atttype_desc_dy',
        ),
        migrations.AlterModelOptions(
            name='companyinfomapping',
            options={'managed': False},
        ),
    ]
