# Generated by Django 4.2.16 on 2025-12-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0076_merge_20251121_1122'),
        ('lcicHome', '0092_add_merge_performance_indexes'),
    ]

    operations = [
    ]
