# Generated by Django 5.0.14 on 2025-11-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0092_merge_0076_merge_20251121_1122_0091_lciccodemaping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfomapping',
            options={'managed': False},
        ),
    ]
