# Generated by Django 4.1 on 2023-09-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0092_alter_enterpriseinfo_lcicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='EnterpriseID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='enLegalStrature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='eneterpriseNameEnglish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='enterpriseNameLao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='foreigninvestorFlag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='investmentCurrency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='regisCertificateNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='regisDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='regisStationOfficeCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='regisStrationOfficeType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='representativeNationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
