# Generated by Django 5.0.14 on 2025-11-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0093_alter_companyinfomapping_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companyinfomapping',
            table='"lcicHome_companyinfomapping"',
        ),
    ]
