# Generated by Django 4.1 on 2023-09-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0093_alter_enterpriseinfo_enterpriseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='enLocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
