# Generated by Django 4.1.13 on 2025-11-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0093_delete_scr_atttype_desc_dy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_equipment_eqi',
            name='insert_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='col_equipment_eqi',
            name='update_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='insert_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='update_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_real_estates',
            name='insert_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_real_estates',
            name='land_regis_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='col_real_estates',
            name='owner_birth_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_real_estates',
            name='spouse_birth_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='col_real_estates',
            name='update_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='companyinfomapping',
            table='"lcicHome_companyinfomapping"',
        ),
    ]
