# Generated by Django 4.1 on 2023-09-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0094_alter_enterpriseinfo_enlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='LCICID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
