# Generated by Django 4.1.13 on 2025-12-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0094_alter_col_equipment_eqi_insert_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralDetailScoring_JSON',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col_type', models.CharField(blank=True, max_length=10, null=True)),
                ('col_type_name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('col_type_name_lao', models.CharField(blank=True, max_length=100, null=True)),
                ('col_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lcic_id', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('value_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditScoringReport_JSON',
            fields=[
                ('SCJ_id', models.AutoField(primary_key=True, serialize=False)),
                ('lcic_id', models.CharField(db_index=True, max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=10, null=True)),
                ('final_credit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetailScoring_JSON',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_id', models.CharField(max_length=50)),
                ('bnk_code', models.CharField(blank=True, max_length=10, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_status', models.CharField(blank=True, max_length=20, null=True)),
                ('loan_open_date', models.DateField(blank=True, null=True)),
                ('loan_exp_date', models.DateField(blank=True, null=True)),
                ('loan_open_year', models.IntegerField(blank=True, null=True)),
                ('loan_term', models.IntegerField(blank=True, null=True)),
                ('loan_purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_line', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('outstanding_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('days_slow', models.IntegerField(blank=True, null=True)),
                ('loan_class', models.CharField(blank=True, max_length=20, null=True)),
                ('loan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_details', to='lcicHome.creditscoringreport_json')),
            ],
        ),
        migrations.CreateModel(
            name='FinalScoring_JSON',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province_score', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status_score', models.CharField(blank=True, max_length=10, null=True)),
                ('age_score', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_year_score', models.CharField(blank=True, max_length=10, null=True)),
                ('loan_purpose_score', models.CharField(blank=True, max_length=10, null=True)),
                ('loan_term_score', models.CharField(blank=True, max_length=10, null=True)),
                ('credit_line_score', models.CharField(blank=True, max_length=10, null=True)),
                ('inquiries_score', models.CharField(blank=True, max_length=10, null=True)),
                ('overdue_class_score', models.CharField(blank=True, max_length=10, null=True)),
                ('collateral_type_score', models.CharField(blank=True, max_length=10, null=True)),
                ('collateral_value_score', models.CharField(blank=True, max_length=10, null=True)),
                ('outstanding_balance_score', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_score', models.IntegerField(blank=True, default=0, null=True)),
                ('final_calculation', models.TextField(blank=True, null=True)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_text', models.CharField(blank=True, max_length=20, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_breakdown', to='lcicHome.creditscoringreport_json')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfoScoring_JSON',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=10, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=10, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('passport', models.CharField(blank=True, max_length=50, null=True)),
                ('familybook', models.CharField(blank=True, max_length=50, null=True)),
                ('familybook_prov_code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('lao_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lao_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ind_insert_date', models.DateField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_info', to='lcicHome.creditscoringreport_json')),
            ],
        ),
        migrations.AddIndex(
            model_name='creditscoringreport_json',
            index=models.Index(fields=['lcic_id', '-created_at'], name='lcicHome_cr_lcic_id_88f197_idx'),
        ),
        migrations.AddField(
            model_name='collateraldetailscoring_json',
            name='loan_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='lcicHome.loandetailscoring_json'),
        ),
        migrations.AddField(
            model_name='collateraldetailscoring_json',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_details', to='lcicHome.creditscoringreport_json'),
        ),
        migrations.AddIndex(
            model_name='loandetailscoring_json',
            index=models.Index(fields=['report', 'loan_status'], name='lcicHome_lo_report__295bba_idx'),
        ),
        migrations.AddIndex(
            model_name='loandetailscoring_json',
            index=models.Index(fields=['loan_id'], name='lcicHome_lo_loan_id_3664c5_idx'),
        ),
        migrations.AddIndex(
            model_name='collateraldetailscoring_json',
            index=models.Index(fields=['report', 'col_type'], name='lcicHome_co_report__b2b1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='collateraldetailscoring_json',
            index=models.Index(fields=['col_id'], name='lcicHome_co_col_id_6b073f_idx'),
        ),
    ]
