# Generated by Django 4.1.13 on 2025-12-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0095_collateraldetailscoring_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetailscoring_json',
            name='loan_term',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
