# Generated by Django 4.1 on 2023-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0096_alter_enterpriseinfo_lcicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='InsertDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
