# Generated by Django 4.1.13 on 2025-12-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0096_alter_loandetailscoring_json_loan_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscoringreport_json',
            name='bnk_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='creditscoringreport_json',
            index=models.Index(fields=['bnk_code', '-created_at'], name='lcicHome_cr_bnk_cod_347e4a_idx'),
        ),
    ]
