# Generated by Django 4.1 on 2023-09-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0097_alter_enterpriseinfo_insertdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorInfo',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterpriseID', models.CharField(blank=True, max_length=50, null=True)),
                ('IsisCodes', models.CharField(blank=True, max_length=255, null=True)),
                ('IsisName', models.CharField(blank=True, max_length=255, null=True)),
                ('InsertDate', models.DateTimeField(blank=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISISCode',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterpriseID', models.CharField(blank=True, max_length=50, null=True)),
                ('investorName', models.CharField(blank=True, max_length=255, null=True)),
                ('investorOwnerPercentage', models.CharField(blank=True, max_length=100, null=True)),
                ('investorNationality', models.CharField(blank=True, max_length=50, null=True)),
                ('investorcardNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('investorMobile', models.CharField(blank=True, max_length=50, null=True)),
                ('InsertDate', models.DateTimeField(blank=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
