# Generated by Django 4.1.13 on 2025-12-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0097_creditscoringreport_json_bnk_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditscoringreport_json',
            name='credit_rating',
        ),
        migrations.RemoveField(
            model_name='creditscoringreport_json',
            name='final_credit_score',
        ),
        migrations.RemoveField(
            model_name='loandetailscoring_json',
            name='loan_open_year',
        ),
        migrations.AddField(
            model_name='creditscoringreport_json',
            name='reference_scr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
