# Generated by Django 4.2.4 on 2023-11-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0098_investorinfo_isiscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterpise_Info_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterpriseID', models.CharField(max_length=200)),
                ('LCICID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='searchList_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_info', models.BooleanField(default=False)),
            ],
        ),
    ]
