# Generated by Django 4.1.13 on 2025-12-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0093_merge_20251203_1443'),
        ('lcicHome', '0098_remove_creditscoringreport_json_credit_rating_and_more'),
    ]

    operations = [
    ]
