# Generated by Django 4.1.13 on 2025-12-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0099_merge_20251204_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_lon_compare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lon_sys_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=30, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=30, null=True)),
                ('loan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lon_open_date', models.CharField(blank=True, max_length=50, null=True)),
                ('lon_exp_date', models.CharField(blank=True, max_length=50, null=True)),
                ('lon_ext_date', models.CharField(blank=True, max_length=50, null=True)),
                ('lon_int_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('lon_purpose_code', models.CharField(blank=True, max_length=50, null=True)),
                ('lon_credit_line', models.CharField(blank=True, max_length=100, null=True)),
                ('lon_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('lon_outstanding_balance', models.CharField(blank=True, max_length=100, null=True)),
                ('lon_account_no', models.CharField(blank=True, max_length=35, null=True)),
                ('lon_no_days_slow', models.CharField(blank=True, max_length=50, null=True)),
                ('lon_class', models.CharField(blank=True, max_length=5, null=True)),
                ('lon_type', models.CharField(blank=True, max_length=10, null=True)),
                ('lon_term', models.CharField(blank=True, max_length=10, null=True)),
                ('lon_status', models.CharField(blank=True, max_length=20, null=True)),
                ('lon_insert_date', models.CharField(blank=True, max_length=50, null=True)),
                ('lon_update_date', models.CharField(blank=True, max_length=50, null=True)),
                ('lon_applied_date', models.CharField(blank=True, max_length=50, null=True)),
                ('is_disputed', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
