# Generated by Django 4.2.4 on 2023-11-10 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0101_investorinfo_isiscodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestorInfo',
        ),
    ]
