# Generated by Django 4.2.4 on 2023-11-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0102_delete_investorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorInfo',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterpriseID', models.CharField(blank=True, max_length=50, null=True)),
                ('IsisCodes', models.CharField(blank=True, max_length=255, null=True)),
                ('IsisName', models.CharField(blank=True, max_length=255, null=True)),
                ('InsertDate', models.DateTimeField(blank=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
