# Generated by Django 4.2.4 on 2023-11-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0103_investorinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestorInfo',
        ),
    ]
