# Generated by Django 4.2.4 on 2023-11-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0104_delete_investorinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isiscode',
            old_name='investorName',
            new_name='IsisCodes',
        ),
        migrations.RemoveField(
            model_name='isiscode',
            name='investorMobile',
        ),
        migrations.RemoveField(
            model_name='isiscode',
            name='investorNationality',
        ),
        migrations.RemoveField(
            model_name='isiscode',
            name='investorOwnerPercentage',
        ),
        migrations.RemoveField(
            model_name='isiscode',
            name='investorcardNumber',
        ),
        migrations.AddField(
            model_name='isiscode',
            name='IsisName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
