# Generated by Django 4.2.4 on 2023-11-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0105_rename_investorname_isiscode_isiscodes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorInfo',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterpriseID', models.CharField(blank=True, max_length=50, null=True)),
                ('investorName', models.CharField(blank=True, max_length=255, null=True)),
                ('investorOwnerPercentage', models.CharField(blank=True, max_length=100, null=True)),
                ('investorNationality', models.CharField(blank=True, max_length=50, null=True)),
                ('investorcardNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('investorMobile', models.CharField(blank=True, max_length=50, null=True)),
                ('InsertDate', models.DateTimeField(blank=True, null=True)),
                ('UpdateDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
