# Generated by Django 4.1 on 2024-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0110_b1_b1_daily_b1_monthly_b1_yearly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_type',
            fields=[
                ('ReportID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.CharField(blank=True, max_length=255, null=True)),
                ('nameE', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
