# Generated by Django 4.1 on 2024-02-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0111_report_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report_type',
        ),
    ]
