# Generated by Django 4.1 on 2024-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0114_user_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_p',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rp_NameL', models.CharField(blank=True, max_length=255, null=True)),
                ('Rp_NameE', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Report_type',
        ),
    ]
