# Generated by Django 4.1 on 2024-02-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0116_report_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report_p',
        ),
        migrations.DeleteModel(
            name='Report_type',
        ),
    ]
