# Generated by Django 4.1 on 2024-02-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0118_rp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_charge_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=255, null=True)),
                ('chg_amount', models.FloatField(default=0, null=True)),
                ('chg_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('insert_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('rtp_code', models.CharField(blank=True, max_length=255, null=True)),
                ('chg_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('user_sys_id', models.CharField(blank=True, max_length=255, null=True)),
                ('LCIC_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('cusType', models.CharField(blank=True, max_length=255, null=True)),
                ('user_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_reference_code', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_insert_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='searchLog',
            fields=[
                ('search_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('LCIC_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('bnk_code', models.CharField(blank=True, max_length=255, null=True)),
                ('cus_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('inquiry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('inquiry_month', models.DateField(blank=True, null=True)),
                ('inquiry_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('com_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('com_location', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_loan_amount', models.FloatField(default=0, null=True)),
                ('rec_loan_amount_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_loan_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_enquiry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cusType', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
