# Generated by Django 4.1 on 2024-03-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0119_request_charge_searchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_charge',
            name='chg_amount',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request_charge',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='request_charge',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
