# Generated by Django 4.1 on 2024-03-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0120_alter_request_charge_chg_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='request_charge',
        ),
    ]
