# Generated by Django 4.1 on 2024-03-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0121_delete_request_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_charge_log',
            fields=[
                ('rec_charge_ID', models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnk_code', models.CharField(blank=True, max_length=255, null=True)),
                ('chg_amount', models.FloatField(blank=True, max_length=255, null=True)),
                ('chg_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('rtp_code', models.CharField(blank=True, max_length=255, null=True)),
                ('chg_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('user_sys_id', models.CharField(blank=True, max_length=255, null=True)),
                ('LCIC_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('cusType', models.CharField(blank=True, max_length=255, null=True)),
                ('user_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_reference_code', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_insert_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
