# Generated by Django 4.1 on 2024-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0122_request_charge_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_charge_log',
            name='rec_charge_ID',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
