# Generated by Django 4.1 on 2024-03-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0123_alter_request_charge_log_rec_charge_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='request_charge_log',
        ),
    ]
