# Generated by Django 5.0.6 on 2024-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0128_alter_b1_bnk_code_alter_b1_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
