# Generated by Django 5.0.6 on 2024-07-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0131_alter_b1_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='FID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
