# Generated by Django 5.0.6 on 2024-07-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0133_b_data_is_damaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_edit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lcicID', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('com_enterprise_code', models.CharField(max_length=100)),
                ('segmentType', models.CharField(max_length=100)),
                ('bnk_code', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('branch_id', models.CharField(max_length=100)),
                ('lon_sys_id', models.CharField(max_length=100)),
                ('loan_id', models.CharField(max_length=100)),
                ('lon_open_date', models.DateField(null=True)),
                ('lon_exp_date', models.DateField(null=True)),
                ('lon_ext_date', models.DateField(null=True)),
                ('lon_int_rate', models.FloatField(default=0)),
                ('lon_purpose_code', models.CharField(max_length=100)),
                ('lon_credit_line', models.FloatField(default=0)),
                ('lon_currency_code', models.CharField(max_length=100)),
                ('lon_outstanding_balance', models.FloatField(default=0)),
                ('lon_account_no', models.CharField(max_length=100)),
                ('lon_no_days_slow', models.IntegerField(default=0)),
                ('lon_class', models.CharField(max_length=100)),
                ('lon_type', models.CharField(max_length=100)),
                ('lon_term', models.CharField(max_length=100)),
                ('lon_status', models.CharField(max_length=100)),
                ('lon_insert_date', models.DateTimeField(null=True)),
                ('lon_update_date', models.DateTimeField(null=True)),
                ('lon_applied_date', models.DateTimeField(null=True)),
                ('is_disputed', models.BigIntegerField(default=0, null=True)),
            ],
        ),
    ]
