# Generated by Django 5.0.6 on 2024-07-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0134_data_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_data_is_damaged',
            name='com_enterprise_code_error',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='b_data_is_damaged',
            name='lcicID_error',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
