# Generated by Django 5.0.6 on 2024-07-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0135_b_data_is_damaged_com_enterprise_code_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_data_is_damaged',
            name='com_enterprise_code_error',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b_data_is_damaged',
            name='lcicID_error',
            field=models.CharField(max_length=100),
        ),
    ]
