# Generated by Django 5.0.6 on 2024-07-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0136_alter_b_data_is_damaged_com_enterprise_code_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedJSONFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
            ],
        ),
    ]
