# Generated by Django 5.0.6 on 2024-07-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0140_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='b1',
            name='period',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
