# Generated by Django 5.0.6 on 2024-07-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0141_b1_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='b1',
            name='id_file',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b1_monthly',
            name='id_file',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b_data_is_damaged',
            name='id_file',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_edit',
            name='id_file',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
