# Generated by Django 5.0.6 on 2024-07-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0143_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b1',
            name='id_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcicHome.file'),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='id_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcicHome.file'),
        ),
        migrations.AlterField(
            model_name='b_data_is_damaged',
            name='id_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcicHome.file'),
        ),
        migrations.AlterField(
            model_name='data_edit',
            name='id_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcicHome.file'),
        ),
    ]
