# Generated by Django 5.0.6 on 2024-07-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0144_alter_b1_id_file_alter_b1_monthly_id_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b1',
            name='id_file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='id_file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b_data_is_damaged',
            name='id_file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data_edit',
            name='id_file',
            field=models.CharField(max_length=100),
        ),
    ]
