# Generated by Django 5.0.6 on 2024-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0145_alter_b1_id_file_alter_b1_monthly_id_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploadFiles/'),
        ),
    ]
