# Generated by Django 5.0.6 on 2024-07-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0146_upload_file_percentage_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='statussubmit',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
