# Generated by Django 5.0.6 on 2024-08-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0147_upload_file_statussubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='b1',
            name='status_customer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
