# Generated by Django 5.0.6 on 2024-08-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0148_b1_status_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='b1_monthly',
            name='status_customer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
