# Generated by Django 5.0.6 on 2024-08-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0150_remove_b1_monthly_status_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('pathfile', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('insertdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
