# Generated by Django 5.0.6 on 2024-08-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0154_collateral_pathfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
