# Generated by Django 5.0.6 on 2024-08-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0157_b_data_is_damaged_lcicid_get'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b_data_is_damaged',
            name='com_enterprise_code_get',
        ),
    ]
