# Generated by Django 5.0.6 on 2024-08-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0158_remove_b_data_is_damaged_com_enterprise_code_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_data_is_damaged',
            name='com_enterprise_code_get',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
