# Generated by Django 5.0.6 on 2024-08-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0159_b_data_is_damaged_com_enterprise_code_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='login',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
