# Generated by Django 5.0.6 on 2024-08-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0160_login_is_staff_login_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnk_code', models.CharField(max_length=30)),
                ('bank_branch_id', models.CharField(max_length=30)),
                ('customer_id', models.CharField(max_length=50)),
                ('loan_id', models.CharField(max_length=50)),
                ('collateral_id', models.CharField(max_length=30)),
                ('collateral_type', models.CharField(max_length=30)),
                ('collateral_status', models.CharField(max_length=30)),
                ('collateral_insert_date', models.DateTimeField(blank=True)),
                ('collateral_update_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
