# Generated by Django 5.0.6 on 2024-08-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0161_c1'),
    ]

    operations = [
        migrations.AddField(
            model_name='c1',
            name='com_enterprise_code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c1',
            name='lcicID',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='c1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
