# Generated by Django 5.0.6 on 2024-08-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0162_c1_com_enterprise_code_c1_lcicid_alter_c1_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='col_real_estate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=25)),
                ('col_provin', models.CharField(max_length=30)),
                ('col_district', models.CharField(max_length=30)),
                ('col_village', models.CharField(max_length=30)),
                ('col_unit', models.CharField(max_length=30)),
                ('col_no', models.CharField(max_length=30)),
                ('col_out_time', models.CharField(max_length=30)),
                ('col_type', models.CharField(max_length=30)),
                ('col_area', models.CharField(max_length=30)),
                ('col_land_registry_book_no', models.CharField(max_length=30)),
                ('col_document_no', models.CharField(max_length=30)),
                ('col_land_map_no', models.CharField(max_length=30)),
                ('col_land_plot_no', models.CharField(max_length=30)),
                ('col_land_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('col_land_unit', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_birth_date', models.DateField()),
                ('owner_nationality', models.CharField(max_length=30)),
                ('owner_occupation', models.CharField(max_length=50)),
                ('current_unit', models.CharField(max_length=30)),
                ('current_village', models.CharField(max_length=30)),
                ('current_district', models.CharField(max_length=30)),
                ('current_provin', models.CharField(max_length=30)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_birth_date', models.DateField(blank=True, null=True)),
                ('spouse_nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('land_acquisition', models.CharField(max_length=100)),
                ('ownership_status', models.CharField(max_length=50)),
                ('insert_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'col_real_estate',
            },
        ),
        migrations.AddField(
            model_name='c1',
            name='insert_date',
            field=models.DateTimeField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c1',
            name='update_date',
            field=models.DateTimeField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
