# Generated by Django 5.0.6 on 2024-08-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0163_col_real_estate_c1_insert_date_c1_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c1',
            name='insert_date',
        ),
        migrations.RemoveField(
            model_name='c1',
            name='update_date',
        ),
    ]
