# Generated by Django 5.0.6 on 2024-08-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0164_remove_c1_insert_date_remove_c1_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='col_equipment_eqi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_customer_id', models.CharField(max_length=30)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=30)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('loan_id', models.CharField(max_length=30)),
                ('collateral_id', models.CharField(max_length=30)),
                ('machine_type', models.CharField(max_length=30)),
                ('machine_no', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('insert_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'col_equipment_eqi',
            },
        ),
        migrations.CreateModel(
            name='col_money_mia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=30)),
                ('bank_customer_ID', models.CharField(max_length=30)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('loan_id', models.CharField(max_length=30)),
                ('collateral_id', models.CharField(max_length=30)),
                ('account_no', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('insert_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'col_money_mia',
            },
        ),
        migrations.CreateModel(
            name='col_project_prj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_customer_id', models.CharField(max_length=30)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=30)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('loan_id', models.CharField(max_length=30)),
                ('project_type', models.CharField(max_length=30)),
                ('collateral_id', models.CharField(max_length=30)),
                ('project_name_en', models.CharField(max_length=30)),
                ('ministry', models.CharField(max_length=30)),
                ('project_namber', models.CharField(max_length=30)),
                ('project_name_la', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('insert_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'col_project_prj',
            },
        ),
    ]
