# Generated by Django 5.0.6 on 2024-08-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0165_col_equipment_eqi_col_money_mia_col_project_prj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='col_equipment_eqi',
        ),
        migrations.DeleteModel(
            name='col_money_mia',
        ),
        migrations.DeleteModel(
            name='col_project_prj',
        ),
        migrations.DeleteModel(
            name='col_real_estate',
        ),
    ]
