# Generated by Django 5.0.6 on 2024-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0166_delete_col_equipment_eqi_delete_col_money_mia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='col_equipment_eqi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_customer_id', models.CharField(max_length=30)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=30)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('loan_id', models.CharField(max_length=30)),
                ('collateral_id', models.CharField(max_length=30)),
                ('machine_type', models.CharField(max_length=30)),
                ('machine_no', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('insert_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'col_equipment_eqi',
            },
        ),
        migrations.CreateModel(
            name='col_money_mia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=30)),
                ('bank_customer_ID', models.CharField(max_length=30)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('loan_id', models.CharField(max_length=30)),
                ('collateral_id', models.CharField(max_length=30)),
                ('account_no', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('insert_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'col_money_mia',
            },
        ),
        migrations.CreateModel(
            name='col_project_prj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_customer_id', models.CharField(max_length=30)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=30)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('loan_id', models.CharField(max_length=30)),
                ('project_type', models.CharField(max_length=30)),
                ('collateral_id', models.CharField(max_length=30)),
                ('project_name_en', models.CharField(max_length=30)),
                ('ministry', models.CharField(max_length=30)),
                ('project_namber', models.CharField(max_length=30)),
                ('project_name_la', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('insert_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'col_project_prj',
            },
        ),
        migrations.CreateModel(
            name='col_real_estate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=25)),
                ('col_provin', models.CharField(max_length=30)),
                ('col_district', models.CharField(max_length=30)),
                ('col_village', models.CharField(max_length=30)),
                ('col_unit', models.CharField(max_length=30)),
                ('col_no', models.CharField(max_length=30)),
                ('col_out_time', models.CharField(max_length=30)),
                ('col_type', models.CharField(max_length=30)),
                ('col_area', models.CharField(max_length=30)),
                ('col_land_registry_book_no', models.CharField(max_length=30)),
                ('col_document_no', models.CharField(max_length=30)),
                ('col_land_map_no', models.CharField(max_length=30)),
                ('col_land_plot_no', models.CharField(max_length=30)),
                ('col_land_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('col_land_unit', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_birth_date', models.DateField()),
                ('owner_nationality', models.CharField(max_length=30)),
                ('owner_occupation', models.CharField(max_length=50)),
                ('current_unit', models.CharField(max_length=30)),
                ('current_village', models.CharField(max_length=30)),
                ('current_district', models.CharField(max_length=30)),
                ('current_provin', models.CharField(max_length=30)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_birth_date', models.DateField(blank=True, null=True)),
                ('spouse_nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('land_acquisition', models.CharField(max_length=100)),
                ('ownership_status', models.CharField(max_length=50)),
                ('insert_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'col_real_estate',
            },
        ),
    ]
