# Generated by Django 5.0.6 on 2024-08-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0167_col_equipment_eqi_col_money_mia_col_project_prj_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='col_real_estate',
        ),
    ]
