# Generated by Django 5.0.6 on 2024-08-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0170_col_goldsilver_gold_col_guarantor_gua_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='col_goldsilver_gold',
        ),
    ]
