# Generated by Django 5.0.6 on 2024-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0171_delete_col_goldsilver_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='col_goldsilver_gold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=30)),
                ('bank_customer_ID', models.CharField(max_length=30)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('loan_id', models.CharField(max_length=30)),
                ('collateral_id', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('insert_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'col_goldsilver_gold',
            },
        ),
    ]
