# Generated by Django 5.0.6 on 2024-08-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0172_col_goldsilver_gold'),
        ('lcicNews', '0021_delete_bank_bnk_delete_bank_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File_C',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=255)),
                ('fileUpload', models.FileField(upload_to='uploadFiles/')),
                ('fileSize', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('statussubmit', models.CharField(max_length=150)),
                ('status_upload', models.CharField(max_length=150)),
                ('FileType', models.CharField(max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
                ('GID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.user_group')),
                ('MID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicNews.memberinfo')),
                ('SType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.stype')),
                ('UType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.upload_type')),
            ],
        ),
    ]
