# Generated by Django 5.0.6 on 2024-08-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0174_col_equipment_eqi_collateral_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_error',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('bank_customer_ID', models.CharField(max_length=50)),
                ('loan_id', models.CharField(max_length=50)),
                ('collateral_id', models.CharField(max_length=30)),
                ('collateral_type', models.CharField(max_length=30)),
                ('datamacth', models.CharField(max_length=30)),
                ('collateral_insert_date', models.DateTimeField(blank=True)),
                ('collateral_update_date', models.DateTimeField(blank=True)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=25)),
            ],
        ),
    ]
