# Generated by Django 5.0.6 on 2024-08-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0175_c_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_error',
            name='collateral_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
