# Generated by Django 5.0.6 on 2024-08-30 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0176_c_error_collateral_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_error',
            old_name='datamacth',
            new_name='datamatch',
        ),
    ]
