# Generated by Django 5.0.6 on 2024-08-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0177_rename_datamacth_c_error_datamatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c1',
            old_name='customer_id',
            new_name='bank_customer_ID',
        ),
    ]
