# Generated by Django 5.0.6 on 2024-08-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0178_rename_customer_id_c1_bank_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c1',
            old_name='bank_branch_id',
            new_name='branch_id_code',
        ),
        migrations.RenameField(
            model_name='c1',
            old_name='collateral_insert_date',
            new_name='insert_date',
        ),
        migrations.RenameField(
            model_name='c1',
            old_name='collateral_update_date',
            new_name='update_date',
        ),
    ]
