# Generated by Django 5.0.6 on 2024-08-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0179_rename_bank_branch_id_c1_branch_id_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_error',
            name='bnk_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='bnk_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_goldsilver_gold',
            name='bnk_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_guarantor_gua',
            name='bnk_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_money_mia',
            name='bnk_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_project_prj',
            name='bnk_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_vechicle_veh',
            name='bnk_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
