# Generated by Django 5.0.6 on 2024-09-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0181_c1_id_file_c_error_id_file_col_equipment_eqi_id_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='C1_disptes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_file', models.CharField(max_length=100)),
                ('bnk_code', models.CharField(max_length=30)),
                ('branch_id_code', models.CharField(max_length=30)),
                ('bank_customer_ID', models.CharField(max_length=50)),
                ('loan_id', models.CharField(max_length=50)),
                ('collateral_id', models.CharField(max_length=30)),
                ('collateral_type', models.CharField(max_length=30)),
                ('collateral_status', models.CharField(max_length=30)),
                ('insert_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
                ('lcicID', models.CharField(max_length=30)),
                ('com_enterprise_code', models.CharField(max_length=25)),
            ],
        ),
    ]
