# Generated by Django 5.0.6 on 2024-09-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0182_c1_disptes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='col_equipment_eqi',
            old_name='bank_customer_id',
            new_name='bank_customer_ID',
        ),
        migrations.RenameField(
            model_name='col_project_prj',
            old_name='bank_customer_id',
            new_name='bank_customer_ID',
        ),
        migrations.AddField(
            model_name='col_real_estates',
            name='bank_customer_ID',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
