# Generated by Django 5.0.6 on 2024-09-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0183_rename_bank_customer_id_col_equipment_eqi_bank_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_real_estates',
            name='branch_id_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_real_estates',
            name='loan_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
