# Generated by Django 5.0.6 on 2024-09-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0184_col_real_estates_branch_id_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_access_all_paths', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('roles', models.ManyToManyField(related_name='sidebar_items', to='lcicHome.role')),
            ],
        ),
        migrations.CreateModel(
            name='SidebarSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='lcicHome.sidebaritem')),
                ('roles', models.ManyToManyField(related_name='sidebar_sub_items', to='lcicHome.role')),
            ],
        ),
    ]
