# Generated by Django 5.0.6 on 2024-09-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0188_c_error_col_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c1',
            name='loan_id',
        ),
    ]
