# Generated by Django 5.0.6 on 2024-09-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0189_remove_c1_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='c1',
            name='loan_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
