# Generated by Django 5.0.6 on 2024-09-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0191_remove_c1_col_id_remove_c1_disptes_col_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='c1',
            name='col_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='c1_disptes',
            name='col_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
