# Generated by Django 5.0.6 on 2024-09-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0192_c1_col_id_c1_disptes_col_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_real_estates',
            name='plot_vilid',
        ),
    ]
