# Generated by Django 5.0.6 on 2024-09-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0195_col_real_estates_col_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_real_estates',
            name='col_unit',
        ),
    ]
