# Generated by Django 5.0.6 on 2024-09-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0196_remove_col_real_estates_col_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_real_estates',
            name='plot_vilid',
        ),
    ]
