# Generated by Django 5.0.6 on 2024-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0197_remove_col_real_estates_plot_vilid'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_real_estates',
            name='plot_vilid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
