# Generated by Django 5.0.6 on 2024-09-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0198_col_real_estates_plot_vilid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_real_estates',
            name='plot_unit',
        ),
    ]
