# Generated by Django 5.0.6 on 2024-09-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0200_col_real_estates_plot_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_real_estates',
            name='col_id',
        ),
    ]
