# Generated by Django 5.0.6 on 2024-09-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0202_col_real_estates_col_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_real_estates',
            name='col_area',
        ),
    ]
