# Generated by Django 5.0.6 on 2024-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0203_remove_col_real_estates_col_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_real_estates',
            name='col_area',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
