# Generated by Django 5.0.6 on 2024-09-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0204_col_real_estates_col_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_registry_book_no',
        ),
    ]
