# Generated by Django 5.0.6 on 2024-09-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0206_col_real_estates_land_registry_book_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_real_estates',
            name='col_document_no',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='current_unit',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='current_vilid',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_document_no',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_map_no',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_no',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_plot_no',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_regis_date',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_type',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_unit',
        ),
        migrations.RemoveField(
            model_name='col_real_estates',
            name='place_regist_no',
        ),
    ]
