# Generated by Django 5.0.6 on 2024-09-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0208_col_real_estates_current_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_real_estates',
            name='land_no',
        ),
    ]
