# Generated by Django 5.0.6 on 2024-09-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0213_col_real_estates_bank_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_money_mia',
            name='loan_id',
        ),
    ]
