# Generated by Django 5.0.6 on 2024-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0214_remove_col_money_mia_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_money_mia',
            name='loan_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
