# Generated by Django 5.0.6 on 2024-09-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0215_col_money_mia_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_money_mia',
            name='col_id',
        ),
    ]
