# Generated by Django 5.0.6 on 2024-09-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0216_remove_col_money_mia_col_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_equipment_eqi',
            name='col_id',
        ),
        migrations.RemoveField(
            model_name='col_equipment_eqi',
            name='loan_id',
        ),
    ]
