# Generated by Django 5.0.6 on 2024-09-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0218_col_equipment_eqi_col_id_col_equipment_eqi_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_equipment_eqi',
            name='loan_id',
        ),
    ]
