# Generated by Django 5.0.6 on 2024-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0219_remove_col_equipment_eqi_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='loan_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
