# Generated by Django 5.0.6 on 2024-09-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0220_col_equipment_eqi_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_equipment_eqi',
            name='col_id',
        ),
    ]
