# Generated by Django 5.0.6 on 2024-09-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0222_col_equipment_eqi_col_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_project_prj',
            name='col_id',
        ),
        migrations.RemoveField(
            model_name='col_project_prj',
            name='loan_id',
        ),
    ]
