# Generated by Django 5.0.6 on 2024-09-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0228_col_project_prj_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_vechicle_veh',
            name='col_id',
        ),
        migrations.RemoveField(
            model_name='col_vechicle_veh',
            name='loan_id',
        ),
    ]
