# Generated by Django 5.0.6 on 2024-09-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0230_col_vechicle_veh_col_id_col_vechicle_veh_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_vechicle_veh',
            name='col_id',
        ),
    ]
