# Generated by Django 5.0.6 on 2024-09-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0232_col_vechicle_veh_col_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_vechicle_veh',
            name='loan_id',
        ),
    ]
