# Generated by Django 5.0.6 on 2024-09-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0235_remove_col_guarantor_gua_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_guarantor_gua',
            name='loan_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
