# Generated by Django 5.0.6 on 2024-09-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0236_col_guarantor_gua_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_guarantor_gua',
            name='col_id',
        ),
    ]
