# Generated by Django 5.0.6 on 2024-09-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0238_col_guarantor_gua_col_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_goldsilver_gold',
            name='loan_id',
        ),
    ]
