# Generated by Django 5.0.6 on 2024-09-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0239_remove_col_goldsilver_gold_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_goldsilver_gold',
            name='loan_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
