# Generated by Django 5.0.6 on 2024-09-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0240_col_goldsilver_gold_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_goldsilver_gold',
            name='col_id',
        ),
    ]
