# Generated by Django 5.0.6 on 2024-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0243_alter_col_real_estates_com_enterprise_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c1',
            name='com_enterprise_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='c1_disptes',
            name='com_enterprise_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='c_error',
            name='com_enterprise_code',
            field=models.CharField(max_length=50),
        ),
    ]
