# Generated by Django 5.0.6 on 2024-09-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0245_col_real_estates_col_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_real_estates',
            name='land_map_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_real_estates',
            name='land_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_real_estates',
            name='place_regist_land',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
