# Generated by Django 5.0.6 on 2024-09-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0246_col_real_estates_land_map_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_real_estates',
            name='land_regis_date',
            field=models.CharField(),
        ),
    ]
