# Generated by Django 5.0.6 on 2024-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0247_alter_col_real_estates_land_regis_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_real_estates',
            name='owner_birth_date',
            field=models.CharField(),
        ),
    ]
