# Generated by Django 5.0.6 on 2024-09-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0248_alter_col_real_estates_owner_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c1',
            old_name='collateral_type',
            new_name='col_type',
        ),
        migrations.RenameField(
            model_name='c1_disptes',
            old_name='collateral_type',
            new_name='col_type',
        ),
        migrations.RenameField(
            model_name='c_error',
            old_name='collateral_type',
            new_name='col_type',
        ),
        migrations.RenameField(
            model_name='col_equipment_eqi',
            old_name='collateral_type',
            new_name='col_type',
        ),
        migrations.RenameField(
            model_name='col_goldsilver_gold',
            old_name='collateral_type',
            new_name='col_type',
        ),
        migrations.RenameField(
            model_name='col_guarantor_gua',
            old_name='collateral_type',
            new_name='col_type',
        ),
        migrations.RenameField(
            model_name='col_money_mia',
            old_name='collateral_type',
            new_name='col_type',
        ),
        migrations.RenameField(
            model_name='col_project_prj',
            old_name='collateral_type',
            new_name='col_type',
        ),
        migrations.RenameField(
            model_name='col_real_estates',
            old_name='collateral_type',
            new_name='col_type',
        ),
        migrations.RenameField(
            model_name='col_vechicle_veh',
            old_name='collateral_type',
            new_name='col_type',
        ),
    ]
