# Generated by Django 5.0.6 on 2024-09-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0249_rename_collateral_type_c1_col_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_real_estates',
            name='spouse_birth_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
