# Generated by Django 5.0.6 on 2024-09-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0250_alter_col_real_estates_spouse_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='col_vechicle_veh',
            old_name='body_numbe',
            new_name='body_number',
        ),
    ]
