# Generated by Django 5.0.6 on 2024-09-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0251_rename_body_numbe_col_vechicle_veh_body_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_money_mia',
            name='col_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
