# Generated by Django 5.0.6 on 2024-09-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0252_col_money_mia_col_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_money_mia',
            name='mia_owner_gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_money_mia',
            name='mia_owner_lao_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_money_mia',
            name='mia_owner_lao_surname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_money_mia',
            name='mia_owner_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_money_mia',
            name='mia_owner_surname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_money_mia',
            name='mia_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_money_mia',
            name='mia_value_unit',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
