# Generated by Django 5.0.6 on 2024-09-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0253_col_money_mia_mia_owner_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='machine_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='owner_lao_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='owner_lao_surname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='owner_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='owner_surname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
