# Generated by Django 5.0.6 on 2024-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0257_col_goldsilver_gold_gld_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c1',
            name='customer_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
