# Generated by Django 5.0.6 on 2024-09-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0258_c1_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c1',
            name='customer_id',
        ),
    ]
