# Generated by Django 5.0.6 on 2024-09-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0259_remove_c1_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='col_money_mia',
            old_name='mia_value_unit',
            new_name='value_unit',
        ),
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='value_unit',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_goldsilver_gold',
            name='value_unit',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_guarantor_gua',
            name='value_unit',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_project_prj',
            name='value_unit',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_vechicle_veh',
            name='value_unit',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
