# Generated by Django 5.0.6 on 2024-09-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0260_rename_mia_value_unit_col_money_mia_value_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_real_estates',
            name='value_unit',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
