# Generated by Django 5.0.6 on 2024-09-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0261_col_real_estates_value_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_vechicle_veh',
            name='vehicle_value_unit',
        ),
    ]
