# Generated by Django 5.0.6 on 2024-09-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0263_rename_mia_owner_gender_col_money_mia_owner_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_equipment_eqi',
            name='owner_gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_guarantor_gua',
            name='owner_gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_real_estates',
            name='owner_gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
