# Generated by Django 5.0.6 on 2024-09-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0264_col_equipment_eqi_owner_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='col_project_prj',
            old_name='project_namber',
            new_name='project_number',
        ),
    ]
