# Generated by Django 5.0.6 on 2024-09-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0267_b1_user_id_b1_monthly_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='user_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
