# Generated by Django 5.0.6 on 2024-09-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0269_file_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
