# Generated by Django 5.0.6 on 2024-09-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0270_alter_file_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='file_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
