# Generated by Django 5.0.6 on 2024-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0271_upload_file_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='b1',
            name='product_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b1_monthly',
            name='product_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b_data_is_damaged',
            name='product_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_edit',
            name='product_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disputes',
            name='product_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
