# Generated by Django 5.0.6 on 2024-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0274_c1_user_id_c1_disptes_user_id_c_error_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file_c',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
