# Generated by Django 5.0.6 on 2024-09-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0275_upload_file_c_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c1', models.CharField(max_length=100)),
                ('c2', models.CharField(max_length=100)),
                ('c3', models.CharField(max_length=100)),
                ('c4', models.CharField(max_length=100)),
                ('c5', models.CharField(max_length=100)),
                ('c6', models.CharField(max_length=100)),
                ('c7', models.CharField(max_length=100)),
                ('c8', models.CharField(max_length=100)),
                ('c9', models.CharField(max_length=100)),
                ('c10', models.CharField(max_length=100)),
                ('c11', models.CharField(max_length=100)),
                ('c12', models.CharField(max_length=100)),
                ('c13', models.CharField(max_length=100)),
                ('c14', models.CharField(max_length=100)),
                ('c15', models.CharField(max_length=100)),
                ('c16', models.CharField(max_length=100)),
                ('c17', models.CharField(max_length=100)),
                ('c18', models.CharField(max_length=100)),
                ('c19', models.CharField(max_length=100)),
                ('c20', models.CharField(max_length=100)),
                ('c21', models.CharField(max_length=100)),
                ('c22', models.CharField(max_length=100)),
                ('c23', models.CharField(max_length=100)),
                ('c24', models.CharField(max_length=100)),
                ('c25', models.CharField(max_length=100)),
                ('c26', models.CharField(max_length=100)),
                ('c27', models.CharField(max_length=100)),
                ('c28', models.CharField(max_length=100)),
                ('c29', models.CharField(max_length=100)),
                ('c30', models.CharField(max_length=100)),
                ('c31', models.CharField(max_length=100)),
                ('c32', models.CharField(max_length=100)),
                ('c33', models.CharField(max_length=100)),
                ('c34', models.CharField(max_length=100)),
                ('c35', models.CharField(max_length=100)),
                ('c36', models.CharField(max_length=100)),
                ('c37', models.CharField(max_length=100)),
                ('c38', models.CharField(max_length=100)),
                ('col_type', models.CharField(max_length=30)),
            ],
        ),
    ]
