# Generated by Django 5.0.6 on 2024-09-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0276_cdl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdl',
            name='c39',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdl',
            name='c40',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdl',
            name='id_file',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
