# Generated by Django 5.0.6 on 2024-09-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0278_cdl_c41'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_real_estates',
            name='owner_name_lao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_real_estates',
            name='owner_surname_lao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_real_estates',
            name='rel_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
