# Generated by Django 5.0.6 on 2024-09-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0282_rename_status_col_money_mia_mia_insert_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdl',
            name='period',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdl',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
