# Generated by Django 5.0.6 on 2024-09-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0283_cdl_period_cdl_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdl',
            name='c42',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
