# Generated by Django 5.0.6 on 2024-09-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0284_cdl_c42'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_money_mia',
            name='account_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='account_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='bank_customer_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='bnk_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='branch_id_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='col_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='col_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='com_enterprise_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='lcicID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='loan_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='mia_insert_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='mia_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='owner_gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='owner_lao_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='owner_lao_surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='owner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='owner_surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='segmentType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='value_unit',
            field=models.CharField(max_length=100),
        ),
    ]
