# Generated by Django 5.0.6 on 2024-09-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0285_alter_col_money_mia_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_money_mia',
            name='insert_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='col_money_mia',
            name='update_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='col_real_estates',
            name='insert_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='col_real_estates',
            name='update_date',
            field=models.CharField(),
        ),
    ]
