# Generated by Django 5.0.6 on 2024-09-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0287_alter_col_equipment_eqi_bank_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_guarantor_com',
            name='owner_gender',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='col_guarantor_com',
            name='segmentType',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
