# Generated by Django 5.0.6 on 2024-10-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0293_customlogintoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
