# Generated by Django 5.0.6 on 2024-10-02 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0294_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_charge',
            name='search_log',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.searchlog'),
            preserve_default=False,
        ),
    ]
