# Generated by Django 5.0.6 on 2024-10-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0295_request_charge_search_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchlog',
            options={'verbose_name': 'Search Log', 'verbose_name_plural': 'Search Logs'},
        ),
        migrations.AddField(
            model_name='searchlog',
            name='sys_usr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='inquiry_month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
