# Generated by Django 5.0.6 on 2024-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0296_alter_searchlog_options_searchlog_sys_usr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeMatrix',
            fields=[
                ('chg_sys_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('chg_code', models.CharField(max_length=50)),
                ('chg_type', models.CharField(max_length=50)),
                ('chg_lao_type', models.CharField(max_length=50)),
                ('chg_desc', models.CharField(max_length=50)),
                ('chg_lao_desc', models.CharField(max_length=50)),
                ('chg_amount', models.FloatField()),
                ('chg_unit', models.CharField(max_length=50)),
            ],
        ),
    ]
