# Generated by Django 5.0.6 on 2024-10-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0297_chargematrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargematrix',
            name='chg_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chargematrix',
            name='chg_desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chargematrix',
            name='chg_lao_desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chargematrix',
            name='chg_lao_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chargematrix',
            name='chg_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chargematrix',
            name='chg_unit',
            field=models.CharField(max_length=100),
        ),
    ]
