# Generated by Django 5.0.6 on 2024-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0298_alter_chargematrix_chg_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='bnk_code',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
