# Generated by Django 5.0.6 on 2024-10-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0299_login_bnk_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='bnk_code',
            field=models.CharField(max_length=150),
        ),
    ]
