# Generated by Django 5.0.6 on 2024-10-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0300_alter_login_bnk_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='bnk_code',
        ),
    ]
