# Generated by Django 5.0.6 on 2024-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0301_remove_login_bnk_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='bank_code',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
