# Generated by Django 5.0.6 on 2024-10-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0302_login_bank_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='bank_code',
        ),
    ]
