# Generated by Django 5.0.6 on 2024-10-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0303_remove_login_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='inquiry_month',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
