# Generated by Django 5.0.6 on 2024-10-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0304_alter_searchlog_inquiry_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='inquiry_month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
