# Generated by Django 5.0.6 on 2024-10-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0305_alter_searchlog_inquiry_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_catalog_cat',
            fields=[
                ('cat_sys_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ct_type', models.CharField(max_length=30)),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_lao_name', models.CharField(max_length=100)),
                ('cat_value', models.CharField(max_length=100)),
                ('cat_is_default', models.IntegerField(max_length=100)),
                ('cat_sort_order', models.IntegerField(max_length=100)),
                ('cat_group', models.IntegerField(max_length=100)),
                ('cat_status', models.IntegerField(max_length=100)),
            ],
        ),
    ]
