# Generated by Django 5.0.6 on 2024-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0306_main_catalog_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_catalog_cat',
            name='cat_group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main_catalog_cat',
            name='cat_is_default',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='main_catalog_cat',
            name='cat_sort_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='main_catalog_cat',
            name='cat_status',
            field=models.IntegerField(),
        ),
    ]
