# Generated by Django 5.0.6 on 2024-10-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0307_alter_main_catalog_cat_cat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_charge',
            name='lon_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
