# Generated by Django 5.0.6 on 2024-10-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0310_userloginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Report_UserRole', models.ManyToManyField(related_name='report_catalog', to='lcicHome.user_group')),
            ],
        ),
    ]
