# Generated by Django 5.0.6 on 2024-10-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0311_reportcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_charge',
            name='bnk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='bnk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
