# Generated by Django 5.0.6 on 2024-11-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0313_alter_searchlog_inquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
