# Generated by Django 5.0.6 on 2024-12-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0314_login_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaritem',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
