# Generated by Django 5.0.6 on 2024-12-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0314_login_profile_picture'),
        ('lcicHome', '0315_sidebaritem_icon_alter_login_profile_image'),
    ]

    operations = [
    ]
