# Generated by Django 5.0.6 on 2024-12-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0317_search_batfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_batfile',
            old_name='FID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='search_batfile',
            name='fileUpload',
            field=models.FileField(upload_to='searchfile/'),
        ),
    ]
