# Generated by Django 5.0.6 on 2024-12-19 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0318_rename_fid_search_batfile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcicID', models.CharField(max_length=255)),
                ('com_enterprise_code', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('enterpriseNameLao', models.CharField(blank=True, max_length=255, null=True)),
                ('investmentCurrency', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcicHome.search_batfile')),
            ],
        ),
    ]
