# Generated by Django 5.0.6 on 2024-12-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0319_searchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_batfile',
            name='searchfals',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search_batfile',
            name='searchtrue',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
