# Generated by Django 5.0.6 on 2024-12-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0320_search_batfile_searchfals_search_batfile_searchtrue'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_batfile',
            name='UID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
