# Generated by Django 5.0.6 on 2025-01-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0323_search_batfile_duplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_batfile',
            name='count_duplicates',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search_batfile',
            name='duplicates_false',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
