# Generated by Django 5.0.6 on 2025-01-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0324_search_batfile_count_duplicates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='duplicates',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search_batfile',
            name='count_duplicates',
            field=models.IntegerField(default=0),
        ),
    ]
