# Generated by Django 5.0.6 on 2025-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0326_alter_searchresult_duplicates'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile_enterpriseinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('insertdate', models.DateTimeField(auto_now_add=True)),
                ('fileUpload', models.FileField(upload_to='searchfile/')),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
