# Generated by Django 5.0.6 on 2025-01-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0327_uploadfile_enterpriseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile_enterpriseinfo',
            name='crete',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfile_enterpriseinfo',
            name='updatedate',
            field=models.CharField(max_length=255),
        ),
    ]
