# Generated by Django 5.0.6 on 2025-01-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0328_uploadfile_enterpriseinfo_crete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile_enterpriseinfo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
