# Generated by Django 5.0.6 on 2025-01-22 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0331_enterpriseinfo_id_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='id_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.uploadfile_enterpriseinfo'),
        ),
    ]
