# Generated by Django 5.0.6 on 2025-01-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0332_alter_enterpriseinfo_id_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
