# Generated by Django 5.0.6 on 2025-01-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0333_alter_enterpriseinfo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEDCompanyInfo',
            fields=[
                ('CompanyID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CompanyInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NEDEnterpriseInfo',
            fields=[
                ('EnterpriseID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('LCICID', models.CharField(max_length=255)),
                ('enterpriseNameLao', models.CharField(max_length=255, null=True)),
                ('enterpriseNameEnglish', models.CharField(max_length=255, null=True)),
                ('regisCertificateNumber', models.CharField(max_length=255, null=True)),
                ('regisDate', models.DateTimeField(null=True)),
                ('enLocation', models.CharField(max_length=255, null=True)),
                ('regisStrationOfficeType', models.CharField(max_length=255, null=True)),
                ('regisStationOfficeCode', models.CharField(max_length=255, null=True)),
                ('enLegalStrature', models.CharField(max_length=255, null=True)),
                ('foreigninvestorFlag', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'EnterpriseInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('BillID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_ID', models.CharField(max_length=100)),
                ('InvoiceNo', models.CharField(max_length=100)),
                ('TypeOfPro', models.CharField(max_length=100)),
                ('Outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Basic_Tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bill_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Debt_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_ID', models.CharField(max_length=100)),
                ('PaymentType', models.CharField(max_length=100)),
                ('Payment_Date', models.CharField(max_length=100)),
                ('InvoiceMonth', models.CharField(max_length=50)),
                ('InvoiceDate', models.CharField(max_length=100)),
                ('DisID', models.CharField(max_length=100)),
                ('ProID', models.CharField(max_length=100)),
                ('InsertDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('UserID', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='DataSubmitUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Utility_type', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.CharField(blank=True, max_length=30, null=True)),
                ('Amount_data', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('customer_id', models.CharField(max_length=150)),
                ('supply_type', models.CharField(max_length=150)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=150)),
                ('basic_tax', models.DecimalField(decimal_places=2, max_digits=150)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=150)),
                ('bill_of_month', models.CharField(max_length=255)),
                ('date_of_issue', models.CharField(max_length=255)),
                ('dis_id', models.CharField(max_length=150)),
                ('pro_id', models.CharField(max_length=150)),
                ('zone', models.CharField(max_length=150)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=150)),
                ('payment_id', models.CharField(max_length=100)),
                ('pay_type', models.CharField(max_length=150)),
                ('payment_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='login',
            name='bnk_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='branch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
