# Generated by Django 5.0.6 on 2025-02-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0334_nedcompanyinfo_nedenterpriseinfo_bill_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
