# Generated by Django 5.0.6 on 2025-02-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0335_delete_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility_Bill',
            fields=[
                ('BillID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_ID', models.CharField(max_length=100)),
                ('InvoiceNo', models.CharField(max_length=100)),
                ('TypeOfPro', models.CharField(max_length=100)),
                ('Outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Basic_Tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bill_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Debt_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_ID', models.CharField(max_length=100)),
                ('PaymentType', models.CharField(max_length=100)),
                ('Payment_Date', models.CharField(max_length=100)),
                ('InvoiceMonth', models.CharField(max_length=50)),
                ('InvoiceDate', models.CharField(max_length=100)),
                ('DisID', models.CharField(max_length=100)),
                ('ProID', models.CharField(max_length=100)),
                ('InsertDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('UserID', models.CharField(max_length=100)),
            ],
        ),
    ]
