# Generated by Django 5.0.6 on 2025-02-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0336_utility_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility_bill',
            name='UserID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
