# Generated by Django 5.0.6 on 2025-02-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0337_alter_utility_bill_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityBillUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
