# Generated by Django 3.2.6 on 2021-08-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.CharField(max_length=100)),
                ('nameE', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('nameL', models.CharField(max_length=100)),
                ('nameE', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='newsType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicNews.newstype'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='userInfo',
            field=models.ManyToManyField(blank=True, to='lcicNews.userInfo'),
        ),
    ]
