# Generated by Django 3.2.6 on 2021-08-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0003_customerinfo_productinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commandL', models.CharField(max_length=50)),
                ('commandE', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcicNews.newsinfo')),
            ],
        ),
    ]
