# Generated by Django 3.2.6 on 2021-08-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0007_districtinfo_memberinfo_membertype_villageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='provinceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.CharField(max_length=250)),
                ('nameE', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='districtinfo',
            options={'verbose_name_plural': 'districtInfo'},
        ),
        migrations.AlterModelOptions(
            name='newstype',
            options={'verbose_name_plural': 'newsType'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'userInfo'},
        ),
        migrations.AlterModelOptions(
            name='villageinfo',
            options={'verbose_name_plural': 'villageInfo'},
        ),
        migrations.RenameField(
            model_name='memberinfo',
            old_name='VillageInfoL',
            new_name='villageInfo',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='DistrictInfoL',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='ProvinceInfoL',
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='dateRegis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='districtInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicNews.districtinfo'),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='provinceInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicNews.provinceinfo'),
        ),
    ]
