# Generated by Django 3.2.6 on 2021-08-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0008_auto_20210812_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='provinceInfo',
            new_name='provInfo',
        ),
        migrations.RenameField(
            model_name='memberinfo',
            old_name='provinceInfo',
            new_name='provInfo',
        ),
    ]
