# Generated by Django 3.2.6 on 2021-08-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0009_auto_20210812_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('nameL', models.CharField(blank=True, max_length=2500, null=True)),
                ('nameE', models.CharField(blank=True, max_length=2500, null=True)),
                ('descL', models.TextField(blank=True, null=True)),
                ('descE', models.TextField(blank=True, null=True)),
                ('dFiles', models.FileField(blank=True, null=True, upload_to='documentUpload')),
                ('published', models.BooleanField(default=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'documentInfo',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ['id'], 'verbose_name_plural': 'ProductInfo'},
        ),
    ]
