# Generated by Django 3.2.6 on 2021-08-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0011_auto_20210813_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='documentInfo',
            new_name='fdocInfo',
        ),
        migrations.RenameModel(
            old_name='documType',
            new_name='fdocType',
        ),
        migrations.AlterModelOptions(
            name='fdocinfo',
            options={'ordering': ['-id'], 'verbose_name_plural': 'fdocInfo'},
        ),
        migrations.RenameField(
            model_name='fdocinfo',
            old_name='documType',
            new_name='fdocType',
        ),
    ]
