# Generated by Django 3.2.6 on 2021-09-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0012_auto_20210813_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='nFiles',
            field=models.FileField(blank=True, null=True, upload_to='uploadNewsFlils'),
        ),
    ]
