# Generated by Django 3.2.6 on 2021-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0013_newsinfo_nfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('nameL', models.CharField(blank=True, max_length=2500, null=True)),
                ('nameE', models.CharField(blank=True, max_length=2500, null=True)),
                ('descL', models.TextField(blank=True, null=True)),
                ('descE', models.TextField(blank=True, null=True)),
                ('jimage', models.FileField(blank=True, null=True, upload_to='jobUpload')),
                ('jfiles', models.FileField(blank=True, null=True, upload_to='jobUpload')),
                ('published', models.BooleanField(default=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'jobsInfo',
                'ordering': ['-id'],
            },
        ),
    ]
