# Generated by Django 4.0.5 on 2022-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0014_jobinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='H_Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trans_LA', models.TextField(blank=True, null=True)),
                ('Trans_EN', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
