# Generated by Django 4.1 on 2023-08-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0015_h_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_bnk',
            fields=[
                ('bnk_sys_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnk_code', models.CharField(max_length=10)),
                ('bnk_short_form', models.CharField(max_length=10)),
                ('bnk_name', models.CharField(max_length=100)),
                ('bnk_lao_name', models.TextField()),
                ('bnk_insert_date', models.DateField(blank=True, null=True)),
                ('bnk_type', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bank_branch',
            fields=[
                ('branch_sys_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=15)),
                ('branch_name', models.CharField(max_length=50)),
                ('Vill', models.CharField(max_length=50)),
                ('Dis', models.CharField(max_length=50)),
                ('Province', models.CharField(max_length=50)),
                ('bnk_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcicNews.bank_bnk')),
            ],
        ),
    ]
