# Generated by Django 4.1 on 2023-08-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0016_bank_bnk_bank_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_bnk',
            name='bnk_type',
            field=models.IntegerField(),
        ),
    ]
