# Generated by Django 4.1 on 2023-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0017_alter_bank_bnk_bnk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_branch',
            name='bnk_code',
            field=models.CharField(max_length=10),
        ),
    ]
