# Generated by Django 4.1 on 2023-08-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0018_alter_bank_branch_bnk_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank_branch',
        ),
    ]
