# Generated by Django 4.2.4 on 2023-11-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0020_bank_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank_bnk',
        ),
        migrations.DeleteModel(
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='fdocinfo',
            name='dFiles',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='nFiles',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='pFiles',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='pimage',
        ),
        migrations.AddField(
            model_name='fdocinfo',
            name='dFilesE',
            field=models.FileField(blank=True, null=True, upload_to='documentUpload/docE'),
        ),
        migrations.AddField(
            model_name='fdocinfo',
            name='dFilesL',
            field=models.FileField(blank=True, null=True, upload_to='documentUpload/docL'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='nFilesE',
            field=models.FileField(blank=True, null=True, upload_to='uploadNewsFlils/uploadNewsFlilsE'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='nFilesL',
            field=models.FileField(blank=True, null=True, upload_to='uploadNewsFlils/uploadNewsFlilsL'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pFilesE',
            field=models.FileField(blank=True, null=True, upload_to='uploadProducts/uploadProductsE'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pFilesL',
            field=models.FileField(blank=True, null=True, upload_to='uploadProducts/uploadProductsL'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pimageE',
            field=models.FileField(blank=True, null=True, upload_to='uploadProducts/uploadProductsE'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pimageL',
            field=models.FileField(blank=True, null=True, upload_to='uploadProducts/uploadProductsL'),
        ),
    ]
