# Generated by Django 5.0.6 on 2024-10-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0021_delete_bank_bnk_delete_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='bnk_code',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
