# Generated by Django 5.0.6 on 2024-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0022_memberinfo_bnk_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='bnk_type',
            field=models.IntegerField(null=True),
        ),
    ]
