# Generated by Django 5.0.6 on 2024-10-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0023_memberinfo_bnk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='bnk_code',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
