# Generated by Django 5.0.6 on 2024-10-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicNews', '0024_alter_memberinfo_bnk_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
