# Generated by Django 5.0.6 on 2025-02-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSecondary',
        ),
    ]
