# Generated by Django 5.0.6 on 2025-02-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility_Test',
            fields=[
                ('TestID', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=200)),
                ('TestDescription', models.TextField()),
                ('TestAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsActive', models.BooleanField(default=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
