# Generated by Django 5.0.6 on 2025-02-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_utility_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utility_test',
            table='utility_bills',
        ),
    ]
