# Generated by Django 5.0.6 on 2025-02-06 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_alter_utility_test_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='test_123',
        ),
    ]
