# Generated by Django 5.0.6 on 2025-02-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_utility_bills_123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utility_Bills',
        ),
        migrations.DeleteModel(
            name='Utility_Bills_123',
        ),
        migrations.DeleteModel(
            name='Utility_Test',
        ),
    ]
