# Generated by Django 5.0.6 on 2025-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_delete_utility_bills_delete_utility_bills_123_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
