# Generated by Django 5.0.6 on 2025-02-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0010_customer_djangomigrations_jsonfilewater_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterModelOptions(
            name='jsonfilewater',
            options={'managed': False},
        ),
    ]
