# Generated by Django 4.2 on 2025-02-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0011_delete_customer_alter_jsonfilewater_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file_detail',
            },
        ),
    ]
