# Generated by Django 4.2 on 2025-02-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0012_filedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJsonFiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'upload_file_detail',
                'managed': False,
            },
        ),
    ]
