# Generated by Django 4.2 on 2025-02-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0014_utility_bill_utilitybillupload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadjsonfiles',
            table='file_detail',
        ),
    ]
