# Generated by Django 4.2 on 2025-02-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0015_alter_uploadjsonfiles_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetail',
            name='file_path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
