# Generated by Django 4.2 on 2025-02-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0016_alter_filedetail_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
