# Generated by Django 4.2 on 2025-02-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0017_filedetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility_bill',
            name='Customer_ID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='InvoiceNo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='PaymentType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='Payment_Date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='Payment_ID',
            field=models.CharField(max_length=255),
        ),
    ]
