# Generated by Django 4.2 on 2025-02-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0018_alter_utility_bill_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility_bill',
            name='Basic_Tax',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='Bill_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='Debt_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='Outstanding',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
