# Generated by Django 4.2 on 2025-02-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0019_alter_utility_bill_basic_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='processed_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filedetail',
            name='file_path',
            field=models.FileField(upload_to='json_uploads/'),
        ),
    ]
