# Generated by Django 4.2 on 2025-02-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0020_filedetail_processed_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility_bill',
            name='PaymentType',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='Payment_Date',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='Payment_ID',
            field=models.CharField(max_length=1000),
        ),
    ]
