# Generated by Django 4.2 on 2025-02-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0021_alter_utility_bill_paymenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility_bill',
            name='PaymentType',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='Payment_Date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='utility_bill',
            name='Payment_ID',
            field=models.TextField(),
        ),
    ]
