# Generated by Django 4.2 on 2025-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0022_alter_utility_bill_paymenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electric_Bill',
            fields=[
                ('BillID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_ID', models.CharField(max_length=255)),
                ('InvoiceNo', models.CharField(max_length=255)),
                ('TypeOfPro', models.CharField(max_length=100)),
                ('Outstanding', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Basic_Tax', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Bill_Amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Debt_Amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Payment_ID', models.TextField()),
                ('PaymentType', models.TextField()),
                ('Payment_Date', models.TextField()),
                ('InvoiceMonth', models.CharField(max_length=50)),
                ('InvoiceDate', models.CharField(max_length=100)),
                ('DisID', models.CharField(max_length=100)),
                ('ProID', models.CharField(max_length=100)),
                ('InsertDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('UserID', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File_Electric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='electric_json_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('processed_items', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'file_electric',
            },
        ),
    ]
