# Generated by Django 4.2 on 2025-03-06 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0025_searchlog_utility_request_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_charge_utility',
            fields=[
                ('rec_sys_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('usr_session_id', models.CharField(max_length=100)),
                ('bnk_code', models.CharField(max_length=100)),
                ('chg_code', models.CharField(max_length=100)),
                ('chg_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chg_unit', models.CharField(max_length=100)),
                ('sys_usr', models.CharField(max_length=100)),
                ('credit_type', models.CharField(max_length=100)),
                ('edl_cusid', models.CharField(blank=True, default='', max_length=100)),
                ('wt_cusid', models.CharField(blank=True, default='', max_length=100)),
                ('tel_cusid', models.CharField(blank=True, default='', max_length=100)),
                ('proID_edl', models.CharField(blank=True, default='', max_length=100)),
                ('proID_wt', models.CharField(blank=True, default='', max_length=100)),
                ('proID_tel', models.CharField(blank=True, default='', max_length=100)),
                ('red_reference_code', models.CharField(max_length=100)),
                ('rec_insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='searchlog_utility',
            name='inquiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchlog_utility',
            name='inquiry_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchlog_utility',
            name='edl_cusid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchlog_utility',
            name='proID_edl',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchlog_utility',
            name='proID_tel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchlog_utility',
            name='proID_wt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchlog_utility',
            name='tel_cusid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchlog_utility',
            name='wt_cusid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='request_charge',
        ),
        migrations.AddField(
            model_name='request_charge_utility',
            name='search_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.searchlog_utility'),
        ),
    ]
