# Generated by Django 4.2 on 2025-03-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0026_request_charge_utility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog_utility',
            name='inquiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
