# Generated by Django 4.2 on 2025-03-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0027_alter_searchlog_utility_inquiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_charge_utility',
            old_name='red_reference_code',
            new_name='rec_reference_code',
        ),
    ]
