# Generated by Django 4.2 on 2025-03-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0028_rename_red_reference_code_request_charge_utility_rec_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_charge_utility',
            name='rec_reference_code',
            field=models.CharField(max_length=255),
        ),
    ]
