# Generated by Django 4.2 on 2025-03-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0029_alter_request_charge_utility_rec_reference_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='edl_customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=100)),
                ('Company_name', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('National_ID', models.CharField(max_length=100)),
                ('Passport', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Dustrict_ID', models.CharField(max_length=100)),
                ('Province_ID', models.CharField(max_length=100)),
                ('Tel', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Cus_type', models.CharField(max_length=100)),
                ('Regis_date', models.CharField(max_length=100)),
            ],
        ),
    ]
