# Generated by Django 4.2 on 2025-03-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0030_edl_customer_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='edl_district_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pro_id', models.CharField(max_length=50)),
                ('dis_id', models.CharField(max_length=50)),
                ('dis_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='edl_province_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pro_id', models.CharField(max_length=50)),
                ('pro_name', models.CharField(max_length=100)),
            ],
        ),
    ]
