# Generated by Django 4.2 on 2025-09-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0032_uploaddatatracking_uploadlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatatracking',
            name='failed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploaddatatracking',
            name='processed_records',
            field=models.IntegerField(default=0),
        ),
    ]
