# Generated by Django 4.2 on 2025-09-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0033_uploaddatatracking_failed_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatatracking',
            name='user_upload',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
