# Generated by Django 4.2 on 2025-09-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0034_alter_uploaddatatracking_user_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatatracking',
            name='success_rates',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
