# Generated by Django 4.2 on 2025-09-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0035_uploaddatatracking_success_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddatatracking',
            name='success_rates',
        ),
    ]
