# Generated by Django 4.2 on 2025-09-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0036_remove_uploaddatatracking_success_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatatracking',
            name='success_rates',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
