# Generated by Django 4.2 on 2025-09-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0037_uploaddatatracking_success_rates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaddatatracking',
            old_name='success_rates',
            new_name='success_rate_fix',
        ),
    ]
