# Generated by Django 4.2 on 2025-09-10 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0038_rename_success_rates_uploaddatatracking_success_rate_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddatatracking',
            name='success_rate_fix',
        ),
    ]
