# Generated by Django 4.2 on 2025-09-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0039_remove_uploaddatatracking_success_rate_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatatracking',
            name='test_update',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
