# Generated by Django 4.2 on 2025-09-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0040_uploaddatatracking_test_update'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='uploaddatatracking',
            new_name='utility_upl_upload__7f1ab5_idx',
            old_name='upload_data_upload__98554f_idx',
        ),
        migrations.RenameIndex(
            model_name='uploaddatatracking',
            new_name='utility_upl_pro_id_3f40ff_idx',
            old_name='upload_data_pro_id_b4682e_idx',
        ),
        migrations.AlterModelTable(
            name='uploaddatatracking',
            table=None,
        ),
        migrations.AlterModelTable(
            name='uploadlog',
            table=None,
        ),
    ]
