# Generated by Django 4.2 on 2025-09-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0041_rename_upload_data_upload__98554f_idx_utility_upl_upload__7f1ab5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddatatracking',
            name='test_update',
        ),
    ]
