# Generated by Django 4.2 on 2025-09-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0042_remove_uploaddatatracking_test_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatatracking',
            name='success_rates',
            field=models.FloatField(default=0.0),
        ),
    ]
