# Generated by Django 4.2 on 2025-09-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0044_uploaddatatracking_success_rates_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadlog',
            name='tracking',
        ),
        migrations.DeleteModel(
            name='UploadDataTracking',
        ),
        migrations.DeleteModel(
            name='UploadLog',
        ),
    ]
