# Generated by Django 4.2 on 2025-09-10 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0045_remove_uploadlog_tracking_delete_uploaddatatracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDataTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(db_index=True, max_length=10)),
                ('pro_name', models.CharField(max_length=100)),
                ('dis_id', models.CharField(db_index=True, max_length=10)),
                ('dis_name', models.CharField(max_length=100)),
                ('upload_month', models.CharField(db_index=True, max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('data_size_mb', models.FloatField(default=0.0)),
                ('upload_started', models.DateTimeField(blank=True, null=True)),
                ('upload_completed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('user_upload', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('api_response_code', models.IntegerField(blank=True, null=True)),
                ('success_rates', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='utility.uploaddatatracking')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='uploaddatatracking',
            index=models.Index(fields=['upload_month', 'status'], name='utility_upl_upload__7f1ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='uploaddatatracking',
            index=models.Index(fields=['pro_id', 'dis_id'], name='utility_upl_pro_id_3f40ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uploaddatatracking',
            unique_together={('pro_id', 'dis_id', 'upload_month')},
        ),
    ]
