# Generated by Django 4.2 on 2025-09-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0046_uploaddatatracking_uploadlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_base_url', models.URLField()),
                ('api_endpoint_template', models.CharField(help_text='API endpoint template with {month} placeholder', max_length=255)),
                ('auth_type', models.CharField(choices=[('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('basic', 'Basic Auth')], default='bearer', max_length=20)),
                ('timeout_seconds', models.IntegerField(default=300)),
                ('max_retries', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaterUploadDataTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_month', models.CharField(help_text='Month in MMYYYY format (e.g., 122024)', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Description of the upload task', max_length=255, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('success_rates', models.FloatField(default=0.0, help_text='Success rate as percentage')),
                ('data_size_mb', models.FloatField(default=0.0, help_text='Size of processed data in MB')),
                ('api_response_code', models.IntegerField(blank=True, help_text='HTTP response code from water supply API', null=True)),
                ('upload_started', models.DateTimeField(blank=True, null=True)),
                ('upload_completed', models.DateTimeField(blank=True, null=True)),
                ('upload_duration', models.FloatField(blank=True, help_text='Upload duration in seconds', null=True)),
                ('user_upload', models.CharField(help_text='Username who initiated the upload', max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('context_data', models.JSONField(blank=True, help_text='Additional context data in JSON format', null=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='utility.wateruploaddatatracking')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='wateruploaddatatracking',
            index=models.Index(fields=['upload_month'], name='utility_wat_upload__05d178_idx'),
        ),
        migrations.AddIndex(
            model_name='wateruploaddatatracking',
            index=models.Index(fields=['status'], name='utility_wat_status_fe513e_idx'),
        ),
        migrations.AddIndex(
            model_name='wateruploaddatatracking',
            index=models.Index(fields=['created_at'], name='utility_wat_created_d71442_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wateruploaddatatracking',
            unique_together={('upload_month',)},
        ),
        migrations.AddIndex(
            model_name='wateruploadlog',
            index=models.Index(fields=['tracking', 'timestamp'], name='utility_wat_trackin_47fbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='wateruploadlog',
            index=models.Index(fields=['log_level'], name='utility_wat_log_lev_6536ea_idx'),
        ),
        migrations.AddIndex(
            model_name='wateruploadlog',
            index=models.Index(fields=['timestamp'], name='utility_wat_timesta_da296f_idx'),
        ),
    ]
