# Generated by Django 4.2 on 2025-10-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0047_watersupplyapiconfig_wateruploaddatatracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatatracking',
            name='customer_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploaddatatracking',
            name='payment_records',
            field=models.IntegerField(default=0),
        ),
    ]
