# Generated by Django 4.2 on 2025-10-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0048_uploaddatatracking_customer_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Company_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Customer_ID',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Dustrict_ID',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Province_ID',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Surname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='edl_customer_info',
            index=models.Index(fields=['Name', 'Province_ID'], name='name_province_idx'),
        ),
        migrations.AddIndex(
            model_name='edl_customer_info',
            index=models.Index(fields=['Surname', 'Province_ID'], name='surname_province_idx'),
        ),
        migrations.AddIndex(
            model_name='edl_customer_info',
            index=models.Index(fields=['Company_name', 'Province_ID'], name='company_province_idx'),
        ),
    ]
