# Generated by Django 5.0.14 on 2025-10-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0049_alter_edl_customer_info_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='w_customer_info',
            options={'managed': False},
        ),
    ]
