# Generated by Django 4.2 on 2025-10-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0050_alter_w_customer_info_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='w_district_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pro_id', models.CharField(max_length=50)),
                ('dis_id', models.CharField(max_length=50)),
                ('dis_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='w_province_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pro_id', models.CharField(max_length=50)),
                ('pro_name', models.CharField(max_length=100)),
            ],
        ),
    ]
