# Generated by Django 4.2 on 2025-10-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0051_w_district_code_w_province_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateruploaddatatracking',
            name='customer_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wateruploaddatatracking',
            name='payment_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wateruploaddatatracking',
            name='success_rates',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='wateruploaddatatracking',
            name='upload_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
