# Generated by Django 4.2 on 2025-10-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0052_wateruploaddatatracking_customer_records_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wateruploaddatatracking',
            options={'verbose_name': 'Water Upload Tracking', 'verbose_name_plural': 'Water Upload Trackings'},
        ),
        migrations.AlterModelOptions(
            name='wateruploadlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Water Upload Log', 'verbose_name_plural': 'Water Upload Logs'},
        ),
        migrations.RemoveIndex(
            model_name='wateruploaddatatracking',
            name='utility_wat_upload__05d178_idx',
        ),
        migrations.RemoveIndex(
            model_name='wateruploaddatatracking',
            name='utility_wat_status_fe513e_idx',
        ),
        migrations.RemoveIndex(
            model_name='wateruploaddatatracking',
            name='utility_wat_created_d71442_idx',
        ),
        migrations.RemoveIndex(
            model_name='wateruploadlog',
            name='utility_wat_trackin_47fbc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='wateruploadlog',
            name='utility_wat_log_lev_6536ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='wateruploadlog',
            name='utility_wat_timesta_da296f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='wateruploaddatatracking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wateruploadlog',
            name='context_data',
        ),
        migrations.AddField(
            model_name='wateruploaddatatracking',
            name='dis_id',
            field=models.CharField(db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wateruploaddatatracking',
            name='dis_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wateruploaddatatracking',
            name='pro_id',
            field=models.CharField(db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wateruploaddatatracking',
            name='pro_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wateruploaddatatracking',
            name='api_response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wateruploaddatatracking',
            name='data_size_mb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wateruploaddatatracking',
            name='upload_month',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='wateruploaddatatracking',
            name='user_upload',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wateruploadlog',
            name='log_level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='wateruploaddatatracking',
            unique_together={('pro_id', 'dis_id', 'upload_month')},
        ),
        migrations.AddIndex(
            model_name='wateruploaddatatracking',
            index=models.Index(fields=['upload_month', 'status'], name='utility_wat_upload__d9853e_idx'),
        ),
        migrations.AddIndex(
            model_name='wateruploaddatatracking',
            index=models.Index(fields=['pro_id', 'dis_id'], name='utility_wat_pro_id_3ffe02_idx'),
        ),
        migrations.RemoveField(
            model_name='wateruploaddatatracking',
            name='description',
        ),
    ]
