# Generated by Django 4.2 on 2025-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0053_alter_wateruploaddatatracking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateruploaddatatracking',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
