# Generated by Django 4.2 on 2025-10-29 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0054_wateruploaddatatracking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='edl_customer_info',
            name='InsertDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edl_customer_info',
            name='UpdateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
