# Generated by Django 4.2 on 2025-10-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0055_edl_customer_info_insertdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='w_customer_info',
            options={},
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='InsertDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='UpdateDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
