# Generated by Django 4.2.16 on 2025-11-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0055_edl_customer_info_insertdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='w_customer_info',
            name='InsertDate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='w_customer_info',
            name='UpdateDate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='w_customer_info',
            index=models.Index(fields=['Name', 'Province_ID'], name='water_name_prov_idx'),
        ),
        migrations.AddIndex(
            model_name='w_customer_info',
            index=models.Index(fields=['Surname', 'Province_ID'], name='water_surname_prov_idx'),
        ),
    ]
