# Generated by Django 4.2 on 2025-10-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0057_w_customer_info_insertdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Company_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Surname',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
