# Generated by Django 4.2.16 on 2025-11-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0057_w_customer_info_insertdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SType', models.CharField(max_length=150)),
                ('nameL', models.CharField(blank=True, max_length=150)),
                ('nameE', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'SegmentType',
                'ordering': ['SType'],
            },
        ),
        migrations.CreateModel(
            name='Telecom_Bill',
            fields=[
                ('Tel_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerID', models.CharField(max_length=100)),
                ('InvoiceNo', models.CharField(max_length=100)),
                ('TypeOfPro', models.CharField(max_length=100)),
                ('Outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BasicTax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BillAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DebtAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentID', models.CharField(max_length=100)),
                ('PaymentType', models.CharField(max_length=100)),
                ('PaymentDate', models.CharField(max_length=100)),
                ('InvoiceMonth', models.CharField(max_length=50)),
                ('InvoiceDate', models.CharField(max_length=100)),
                ('DisID', models.CharField(max_length=100)),
                ('ProID', models.CharField(max_length=100)),
                ('InsertDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('UserID', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='w_customer_info',
            options={},
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Company_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='InsertDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='Surname',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='edl_customer_info',
            name='UpdateDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UploadFileTelecom',
            fields=[
                ('TID', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=255)),
                ('fileName', models.CharField(max_length=255)),
                ('fileUpload', models.FileField(upload_to='uploadTelecom/')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('telecomType', models.CharField(max_length=255)),
                ('fileSize', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('status_upload', models.CharField(max_length=150)),
                ('FileType', models.CharField(max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
                ('SType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.stype')),
            ],
        ),
    ]
