# Generated by Django 4.2.16 on 2025-11-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0059_stype_telecom_bill_alter_w_customer_info_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomCustomer',
            fields=[
                ('TC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('No', models.CharField(blank=True, default='', max_length=100)),
                ('Customer_ID', models.CharField(db_index=True, max_length=100)),
                ('Company_name', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('Name', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('Surname', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('National_ID', models.CharField(blank=True, default='', max_length=100)),
                ('Passport', models.CharField(blank=True, default='', max_length=100)),
                ('Address', models.TextField(blank=True, default='')),
                ('Dustrict_ID', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('Province_ID', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('Tel', models.CharField(blank=True, default='', max_length=100)),
                ('Email', models.CharField(blank=True, default='', max_length=100)),
                ('Cus_type', models.CharField(blank=True, default='', max_length=100)),
                ('Regis_date', models.CharField(blank=True, default='', max_length=100)),
                ('InsertDate', models.CharField(blank=True, max_length=50, null=True)),
                ('UpdateDate', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
