# Generated by Django 4.2.16 on 2025-11-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0060_telecomcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Province_ID',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True),
        ),
    ]
