# Generated by Django 4.2.16 on 2025-11-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0061_alter_telecomcustomer_province_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telecom_bill',
            old_name='BasicTax',
            new_name='Basic_Tax',
        ),
        migrations.RenameField(
            model_name='telecom_bill',
            old_name='CustomerID',
            new_name='BillID',
        ),
        migrations.RenameField(
            model_name='telecom_bill',
            old_name='BillAmount',
            new_name='Bill_Amount',
        ),
        migrations.RenameField(
            model_name='telecom_bill',
            old_name='PaymentDate',
            new_name='Customer_ID',
        ),
        migrations.RenameField(
            model_name='telecom_bill',
            old_name='DebtAmount',
            new_name='Debt_Amount',
        ),
        migrations.RenameField(
            model_name='telecom_bill',
            old_name='PaymentID',
            new_name='Payment_Date',
        ),
        migrations.RenameField(
            model_name='telecom_bill',
            old_name='Tel_ID',
            new_name='TB_ID',
        ),
        migrations.AddField(
            model_name='telecom_bill',
            name='Payment_ID',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
