# Generated by Django 4.2.16 on 2025-11-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0062_rename_basictax_telecom_bill_basic_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecom_bill',
            name='Basic_Tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='BillID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Bill_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Customer_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Debt_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='DisID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='InsertDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='InvoiceDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='InvoiceMonth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='InvoiceNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='PaymentType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Payment_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Payment_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='ProID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='TypeOfPro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='UpdateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
