# Generated by Django 4.2.16 on 2025-11-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0064_alter_telecom_bill_basic_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecom_bill',
            name='Basic_Tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Bill_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Debt_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
