# Generated by Django 4.2.16 on 2025-11-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0065_alter_telecom_bill_basic_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiletelecom',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='Debt_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
