# Generated by Django 4.2.16 on 2025-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0066_uploadfiletelecom_no_alter_telecom_bill_debt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiletelecom',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
