# Generated by Django 4.2.16 on 2025-11-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0067_alter_uploadfiletelecom_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiletelecom',
            name='no',
        ),
        migrations.AlterField(
            model_name='telecom_bill',
            name='TB_ID',
            field=models.AutoField(db_column='TB_ID', primary_key=True, serialize=False),
        ),
    ]
