# Generated by Django 4.2.16 on 2025-11-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0068_remove_uploadfiletelecom_no_alter_telecom_bill_tb_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telecom_Bill',
        ),
    ]
