# Generated by Django 4.2.16 on 2025-11-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0069_delete_telecom_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telecom_Bill',
            fields=[
                ('TB_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BillID', models.CharField(blank=True, max_length=100, null=True)),
                ('Customer_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('InvoiceNo', models.CharField(blank=True, max_length=100, null=True)),
                ('TypeOfPro', models.CharField(blank=True, max_length=100, null=True)),
                ('Outstanding', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Basic_Tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Bill_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Debt_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('Payment_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('PaymentType', models.CharField(blank=True, max_length=100, null=True)),
                ('Payment_Date', models.CharField(blank=True, max_length=100, null=True)),
                ('InvoiceMonth', models.CharField(blank=True, max_length=50, null=True)),
                ('InvoiceDate', models.CharField(blank=True, max_length=100, null=True)),
                ('DisID', models.CharField(blank=True, max_length=100, null=True)),
                ('ProID', models.CharField(blank=True, max_length=100, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True)),
                ('UserID', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
