# Generated by Django 4.2.16 on 2025-11-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0070_telecom_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecom_bill',
            name='telecomType',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telecomcustomer',
            name='telecomType',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Customer_ID',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
