# Generated by Django 5.0.14 on 2025-11-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0070_telecom_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Customer_ID',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
