<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-11-18 08:49
=======
<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-11-18 08:49
=======
>>>>>>> 25b744b18a90e984956f78fcff9554ba22e13783
# Generated by Django 4.2.16 on 2025-11-18 11:00
>>>>>>> ea817adc79a922cfd2c6cc9f5405f0628154e3ef

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0070_telecom_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Customer_ID',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
