# Generated by Django 4.2.16 on 2025-11-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0071_telecom_bill_telecomtype_telecomcustomer_telecomtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecomcustomer',
            name='National_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Passport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Regis_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
