# Generated by Django 4.2.16 on 2025-11-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0071_alter_telecomcustomer_customer_id'),
        ('utility', '0072_alter_telecomcustomer_email_and_more'),
    ]

    operations = [
    ]
