<<<<<<< HEAD
# Generated by Django 4.2.16 on 2025-11-20 11:06
=======
# Generated by Django 5.0.14 on 2025-11-23 05:43
>>>>>>> 006e6efde6d29fe94d99d8bbc138297067cfdbb9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0073_merge_20251119_1602'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telecomcustomer',
            index=models.Index(fields=['Company_name', 'Province_ID'], name='telecom_company_province_idx'),
        ),
        migrations.AddIndex(
            model_name='telecomcustomer',
            index=models.Index(fields=['Name', 'Province_ID'], name='telecom_name_province_idx'),
        ),
        migrations.AddIndex(
            model_name='telecomcustomer',
            index=models.Index(fields=['Surname', 'Province_ID'], name='telecom_surname_province_idx'),
        ),
    ]
