# Generated by Django 4.2.16 on 2025-11-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0073_merge_20251121_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Company_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Dustrict_ID',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='telecomcustomer',
            name='Surname',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='telecomcustomer',
            index=models.Index(fields=['Company_name', 'Province_ID'], name='telecom_company_province_idx'),
        ),
        migrations.AddIndex(
            model_name='telecomcustomer',
            index=models.Index(fields=['Name', 'Province_ID'], name='telecom_name_province_idx'),
        ),
        migrations.AddIndex(
            model_name='telecomcustomer',
            index=models.Index(fields=['Surname', 'Province_ID'], name='telecom_surname_province_idx'),
        ),
    ]
