# Generated by Django 5.0.14 on 2025-11-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0074_alter_telecomcustomer_address_and_more'),
        ('utility', '0074_telecomcustomer_telecom_company_province_idx_and_more'),
    ]

    operations = [
    ]
