# Generated by Django 3.2.6 on 2021-08-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H_imageBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nameL', models.CharField(max_length=500)),
                ('nameE', models.CharField(max_length=500)),
                ('detailL', models.TextField(blank=True, null=True)),
                ('detailE', models.TextField(blank=True, null=True)),
                ('imageBar', models.FileField(blank=True, null=True, upload_to='upload')),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'ImageBar',
                'ordering': ['-id'],
            },
        ),
    ]
