# Generated by Django 3.2.6 on 2021-09-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0005_auto_20210817_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='h_newsinfo',
            options={'ordering': ['-id'], 'verbose_name_plural': 'newsInfo'},
        ),
    ]
