# Generated by Django 4.0.5 on 2022-07-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0009_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.CharField(max_length=150)),
                ('nameE', models.CharField(max_length=150)),
            ],
        ),
    ]
