# Generated by Django 4.1 on 2022-09-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0012_alter_menu_options_alter_user_group_options_submenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='UID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
