# Generated by Django 4.1 on 2023-01-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0016_alter_customerwater_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='fileUpload',
            field=models.FileField(upload_to='media/fileUploads'),
        ),
    ]
