# Generated by Django 4.1 on 2023-02-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0024_segmenttype_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='SType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lcicHome.segmenttype'),
        ),
    ]
