# Generated by Django 4.1 on 2023-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0030_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmenttype',
            old_name='SName',
            new_name='nameE',
        ),
        migrations.AddField(
            model_name='segmenttype',
            name='nameL',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
