# Generated by Django 4.1 on 2023-06-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0044_stype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SType',
        ),
    ]
