# Generated by Django 4.1 on 2023-06-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0049_b1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='B1',
        ),
    ]
