# Generated by Django 4.1 on 2023-06-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0062_a2'),
    ]

    operations = [
        migrations.CreateModel(
            name='B1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcicID', models.CharField(max_length=25, null=True)),
                ('enterprise_code', models.CharField(max_length=25)),
                ('segmentType', models.CharField(max_length=5)),
                ('customer_id', models.CharField(max_length=30)),
                ('branch_id', models.CharField(max_length=30)),
                ('loan_id', models.CharField(max_length=30)),
                ('lon_open_date', models.DateField(blank=True)),
                ('lon_exp_date', models.DateField(blank=True)),
                ('lon_ext_date', models.DateField(blank=True, default='0000-00-00')),
                ('lon_int_rate', models.FloatField(default=0, null=True)),
                ('lon_purpose_code', models.CharField(max_length=30)),
                ('lon_credit_line', models.IntegerField(default=0, null=True)),
                ('lon_currency_code', models.CharField(max_length=10)),
                ('lon_outstanding_balance', models.IntegerField(default=0, null=True)),
                ('lon_account_no', models.CharField(max_length=30)),
                ('lon_no_days_slow', models.CharField(max_length=30)),
                ('lon_class', models.CharField(max_length=5)),
                ('lon_type', models.CharField(max_length=5)),
                ('lon_term', models.CharField(max_length=25)),
                ('lon_status', models.CharField(max_length=5)),
                ('lon_update_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
