# Generated by Django 4.1 on 2023-08-01 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0066_alter_a2_is_disputed_alter_a2_lon_credit_line_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='B1',
        ),
    ]
