# Generated by Django 4.1 on 2023-08-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0069_b1_daily_b1_monthly_b1_yearly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='B1_Daily',
        ),
        migrations.DeleteModel(
            name='B1_Monthly',
        ),
        migrations.DeleteModel(
            name='B1_Yearly',
        ),
    ]
