# Generated by Django 5.0.6 on 2024-07-29 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0126_login_last_login_alter_login_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B_Data_is_damaged',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_file', models.CharField(max_length=100)),
                ('lcicID', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('lcicID_error', models.CharField(max_length=100)),
                ('com_enterprise_code_error', models.CharField(max_length=100)),
                ('com_enterprise_code', models.CharField(max_length=100)),
                ('segmentType', models.CharField(max_length=100)),
                ('bnk_code', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('branch_id', models.CharField(max_length=100)),
                ('lon_sys_id', models.CharField(max_length=100)),
                ('loan_id', models.CharField(max_length=100)),
                ('lon_open_date', models.DateField(null=True)),
                ('lon_exp_date', models.DateField(null=True)),
                ('lon_ext_date', models.DateField(null=True)),
                ('lon_int_rate', models.FloatField(default=0)),
                ('lon_purpose_code', models.CharField(max_length=100)),
                ('lon_credit_line', models.FloatField(default=0)),
                ('lon_currency_code', models.CharField(max_length=100)),
                ('lon_outstanding_balance', models.FloatField(default=0)),
                ('lon_account_no', models.CharField(max_length=100)),
                ('lon_no_days_slow', models.IntegerField(default=0)),
                ('lon_class', models.CharField(max_length=100)),
                ('lon_type', models.CharField(max_length=100)),
                ('lon_term', models.CharField(max_length=100)),
                ('lon_status', models.CharField(max_length=100)),
                ('lon_insert_date', models.DateTimeField(null=True)),
                ('lon_update_date', models.DateTimeField(null=True)),
                ('lon_applied_date', models.DateTimeField(null=True)),
                ('is_disputed', models.BigIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_edit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_file', models.CharField(max_length=100)),
                ('lcicID', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('com_enterprise_code', models.CharField(max_length=100)),
                ('segmentType', models.CharField(max_length=100)),
                ('bnk_code', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('branch_id', models.CharField(max_length=100)),
                ('lon_sys_id', models.CharField(max_length=100)),
                ('loan_id', models.CharField(max_length=100)),
                ('lon_open_date', models.DateField(null=True)),
                ('lon_exp_date', models.DateField(null=True)),
                ('lon_ext_date', models.DateField(null=True)),
                ('lon_int_rate', models.FloatField(default=0)),
                ('lon_purpose_code', models.CharField(max_length=100)),
                ('lon_credit_line', models.FloatField(default=0)),
                ('lon_currency_code', models.CharField(max_length=100)),
                ('lon_outstanding_balance', models.FloatField(default=0)),
                ('lon_account_no', models.CharField(max_length=100)),
                ('lon_no_days_slow', models.IntegerField(default=0)),
                ('lon_class', models.CharField(max_length=100)),
                ('lon_type', models.CharField(max_length=100)),
                ('lon_term', models.CharField(max_length=100)),
                ('lon_status', models.CharField(max_length=100)),
                ('lon_insert_date', models.DateTimeField(null=True)),
                ('lon_update_date', models.DateTimeField(null=True)),
                ('lon_applied_date', models.DateTimeField(null=True)),
                ('is_disputed', models.BigIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploadFiles/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedJSONFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='b1',
            name='id_file',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='b1',
            name='period',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b1_monthly',
            name='id_file',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b1',
            name='bnk_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='b1',
            name='branch_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='b1',
            name='com_enterprise_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='customer_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='b1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lcicID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='loan_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_account_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_applied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_credit_line',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_ext_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_insert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_int_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_no_days_slow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_purpose_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_sys_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='lon_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='segmentType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='bnk_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='branch_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='com_enterprise_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='customer_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lcicID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='loan_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_account_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_applied_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_credit_line',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_currency_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_ext_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_insert_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_int_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_no_days_slow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_open_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_outstanding_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_purpose_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_sys_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_term',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='lon_update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='b1_monthly',
            name='segmentType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='FID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='b1',
            unique_together={('bnk_code', 'branch_id', 'customer_id', 'loan_id')},
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('size', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
