# Generated by Django 5.0.6 on 2024-07-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0127_b_data_is_damaged_data_edit_file_uploadedjsonfile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='B_Data_is_damaged',
        ),
    ]
