# Generated by Django 5.0.6 on 2024-08-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0131_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
