# Generated by Django 5.0.6 on 2024-08-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0133_customlogintoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomLoginToken',
        ),
    ]
