# Generated by Django 5.0.6 on 2024-08-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcicHome', '0135_customlogintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_access_all_paths', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=255)),
                ('roles', models.ManyToManyField(related_name='accessible_paths', to='lcicHome.role')),
            ],
        ),
    ]
